casper-network/docs

source/docs/casper/economics/delegation.md, source/docs/casper/economics/gas-concepts.md, source/docs/casper/workflow/staking.md
Sections checked: How To's, Design, Economics, and Staking
=> Fixed links and reference to images

source/docs/casper/workflow/index.md
The main branch was not protected and I checked in a link that was part of another PR. Fixing the link and the build now with this PR.
=> Fix build and link

source/docs/casper/workflow/account-hash.md, source/docs/casper/workflow/index.md
Added content to describe account-hash and how to generate it.
=> Added a topic on creating account hash

source/docs/casper/workflow/signer-guide.md
- Added password requirements.
- Added connected sites
- Minor formatting changes
=> Update Signer guide 

.github/CODEOWNERS, source/docs/casper/workflow/staking.md
- update staking page image url
- update codeowners
=> [BUG] staking page images not showing

source/docs/casper/operators/hardware.md
Moving content from the old docs here: https://github.com/casper-network/docs/pull/350/files.
@Buddhika-Pathirathna please review next sprint when you get a chance. Thank you!
=> Move Pr 350 from old docs

source/docs/casper/workflow/signer-guide.md
Signed-off-by: Muhammet Kara <muhammet@make.services>
=> Ledger generates its own keys

source/docs/casper/dapp-dev-guide/getting-started.md, source/docs/casper/faq/faq-developer.md, source/docs/casper/faq/faq-general.md, source/docs/casper/workflow/deploy-transfer.md, source/docs/casper/workflow/erc-20-sample-guide/approvals.md, source/docs/casper/workflow/erc-20-sample-guide/final-balance.md, source/docs/casper/workflow/erc-20-sample-guide/query.md, source/docs/casper/workflow/erc-20-sample-guide/transfers.md, source/docs/casper/workflow/signer-guide.md
- resolve broken links issues
- resolve faq page image not loading in build version
=> [FIX][FAQ] links and image

source/docs/casper/dapp-dev-guide/testing.md
- resolve image error of testing page in build time
=> [BUG] testing image

source/docs/casper/dapp-dev-guide/tutorials/erc20/index.md, source/docs/casper/dapp-dev-guide/tutorials/erc20/tests.md, source/docs/casper/workflow/signer-guide.md, source/docs/casper/workflow/token-transfer.md, src/html/footer.html
- replace original site urls with new one
=> [BUG] replace original docs app links

source/docs/casper/operators/hardware.md
=> Update hardware required to 2TB

source/docs/casper/workflow/signer-guide.md
- Updated guide to reflect that only secret key is downloaded instead of the set of all three keys
=> Reflect latest changes to signer app

.github/workflows/main.yml
- Reverting PR: https://github.com/casper-network/docs/pull/172
- New PR pending this change to be applied: https://github.com/casper-network/docs/pull/174
Removing the coditional upload to allow the new feature with the local tests documented in the PR#174 to merge and work correctly.
=> Reverting cond upload(PR#172) for depl artifact as it interferes with feature in PR#174

source/docs/casper/dapp-dev-guide/tutorials/multi-sig/client.md, source/docs/casper/dapp-dev-guide/tutorials/multi-sig/concepts.md, source/docs/casper/dapp-dev-guide/tutorials/multi-sig/contract.md
Card #57 
Contract
- Removed outdated screenshots of the output
- Updated the commands for building a contract
- Updated the functions table to list only the functions that can be used for key management
Client
- Removed nctl-compile command
- Added command to activate nctl environment
- Added instruction to include absolute path for the BASE_KEY_PATH
- Added list of steps involved in the client code executions 
- Removed all explanation of client code 
- Added more explanation for each step in the client example output
- Updated all instances of the sample output for the client example
- Commented out new section for Key Management Restrictions /rules (to test the rules and add examples in next PR)
=> Multi-sig tutorial updates to contract and client pages

source/docs/casper/faq/faq-developer.md, source/docs/casper/faq/faq-general.md
Additional FAQ updates based on several Slack conversations as per card #117 
Added the following questions to the Developer FAQ:
(Under individual subheadings)
'What factors case the APIError::InvalidPurse' error?'
'What causes an 'ApiError::MissingArgument [2]' error?
(Under CSPR Transactions)
'When is the balance updated after a transaction?'
'How do I ensure sufficient balance during multiple transfers?'
And the following question to the General FAQ:
'What is the minimum CSPR balance required to transfer?'
Pages ran locally without issue.
=> FAQ Updates as per card #117

config/navbar.config.js
https://github.com/casper-network/docs/issues/171
=> MODIFIED: added discord link

source/docs/casper/dapp-dev-guide/keys.md
Modified funding note as per comment on [docs ](https://casperlabs-team.slack.com/archives/C0135SDEGUC/p1644845718289229) channel.
=> Modified funding note

source/docs/casper/dapp-dev-guide/sdk/csharp-sdk.md, source/docs/casper/dapp-dev-guide/sdk/index.md
n/a
Updates to C# SDK page.
n/a
=> Updated C# SDK page.

source/docs/casper/faq/faq-general.md, source/docs/casper/faq/faq-validator.md, source/docs/casper/workflow/ledger-setup.md
[Add Ledger support link #238](https://github.com/casper-network/docs/issues/238)
I've added the link to the Casper setup guide [from Ledger's documentation site](https://support.ledger.com/hc/en-us/articles/4416379141009-Casper-CSPR-?docs=true) to both the FAQ and the Ledger Setup page in our own docs. I've also removed the Validator FAQ question in relation to Ledger support as it is no longer valid.
I did not see any references to Developer Mode in the Ledger Setup guide - if I missed something, I will be happy to revise quickly in the morning.
=> 238 ledger updates

config/sidebar.config.js, source/docs/casper/dapp-dev-guide/list-cspr.md
Card #232 
Added topic for Listing CSPR
- I've added this topic in the Dev guide section, if you see any better fit please let know.
=> New topic for Listing CSPR

source/docs/casper/index.md
=> Fix grammar errors

source/docs/casper/design/serialization-standard.md
Fixes #252
Added `PublicKey` to the Seritalization Tag table.
~
=> Added `PublicKey` to the Seritalization Tag table.

src/assets/scss/theme.scss
https://github.com/casper-network/docs/issues/267
- Added missing second level sublist styles.
- Fixed other small padding discrepancies.
=> FIXED: added proper level 2 sublist styling

config/color.config.js, config/site.config.js, package.json, source/docs/casper/dapp-dev-guide/deploying-contracts.md, source/docs/casper/dapp-dev-guide/sdk/python-sdk.md, source/docs/casper/dapp-dev-guide/testing.md, source/docs/casper/dapp-dev-guide/tutorials/counter/setup.md, source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md, source/docs/casper/dapp-dev-guide/upgrading-contracts.md, source/docs/casper/design/checksummed-hex.md, source/docs/casper/faq/faq-developer.md, source/docs/casper/faq/faq-validator.md, source/docs/casper/operators/bonding.md, source/docs/casper/operators/joining.md, source/docs/casper/operators/setup.md, source/docs/casper/workflow/deploy-transfer.md, source/docs/casper/workflow/signer-guide.md, source/docs/casper/workflow/testnet-faucet.md, source/docs/casper/workflow/token-transfer.md, yarn.lock
https://github.com/casper-network/docs/issues/268
* enabled `trailingSlash` in the docusaurus configuration
* fixed newly found broken links related to this change
* updated docusaurus and related packages to the latest docusaurus version `2.0.0-beta.17`
* small changes related to breaking changes in the new docusaurus release
I've enabled `trailingSlash` in the docusaurus configuration.
This may solve the issue described here: https://github.com/casper-network/docs/issues/268
This change has in turn caused or found broken internal links:
These have been fixed:
The only way we will know if this improves the formentioned issue though, is for us to deploy this branch.
=> 268 navigation issues with docs

source/docs/casper/dapp-dev-guide/why-build-on-casper.md
Updated the Ledger url to point to their support documentation.
=> Improved Ledger url to point to docs

.github/workflows/main.yml, README.md, docusaurus.config.js, source/docs/casper/dapp-dev-guide/list-cspr.md, source/docs/casper/dapp-dev-guide/sdk/index.md, source/docs/casper/dapp-dev-guide/testing.md, source/docs/casper/dapp-dev-guide/tutorials/cep47/deploy.md, source/docs/casper/dapp-dev-guide/tutorials/cep47/implementation.md, source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md, source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md, source/docs/casper/dapp-dev-guide/why-build-on-casper.md, source/docs/casper/dapp-dev-guide/writing-contracts/rust.md, source/docs/casper/economics/consensus.md, source/docs/casper/faq/faq-developer.md, source/docs/casper/faq/faq-general.md, source/docs/casper/workflow/erc-20-sample-guide/index.md, source/docs/casper/workflow/erc20-token-deployment-guide.md, source/docs/casper/workflow/staking.md, source/i18n/en/docusaurus-plugin-content-docs/current/casper/dapp-dev-guide/setup-nctl.md, source/i18n/en/docusaurus-plugin-content-docs/current/casper/dapp-dev-guide/tutorials/multi-sig/contract.md, source/i18n/en/docusaurus-plugin-content-docs/current/casper/workflow/ledger-setup.md, source/i18n/en/docusaurus-plugin-content-docs/current/casper/workflow/staking.md, src/html/footer.html
After setting up the custom domain docs.casperlabs.io the baseUrl changed.
Without this change the site do not render properly and displays a warning.
=> Fix baseUrl

source/i18n/en/docusaurus-plugin-content-docs/current/casper/workflow/setup.md
Requirements in card #260.
- Added a very brief description that the faucet can only be invoked once.
=> Minor clarification for the faucet

source/docs/casper/workflow/erc-20-sample-guide/approvals.md, source/docs/casper/workflow/erc-20-sample-guide/final-balance.md, source/docs/casper/workflow/erc-20-sample-guide/setup.md, source/docs/casper/workflow/erc-20-sample-guide/transfers.md
No related GitHub issue. I found this while searching the docs.
Remove client name from examples.
=> Update path in examples

source/docs/casper/dapp-dev-guide/why-build-on-casper.md
No related issue; I found this by testing the docs.casperlabs.io switch today.
- Fixed broken links
=> Fixed broken links

.github/workflows/main.yml
This PR enables for the publishing of a staging site to AWS S3.
This includes testing and rollback in case of errors.
=> Bradjohnl gh 265 enable cicd for docs

.github/workflows/dev_main_sync.yml
This PR enables the handling of the automated creation of a PR to merge dev to main at every merge of a feature branch into dev.
This allows for flawless syncing of changes between the staging site and prod site without intervention from a technical person to manually sync changes.
Only the review approval would be necessary like an normal PR to approve and merge.
After that a new deployment starts with the merged contant to the prod site.
For that I had to use a GH App I created for this purpose that can be used in our organization only.
=> Auto merge bot GH action

.github/workflows/dev_main_sync.yml, .github/workflows/main.yml
Fixing the errors in the CI seen in the first tests
=> Bradjohnl final sync dev to main

.github/workflows/main.yml
=> Fix S3 to use http and delete the git folder when publishing

.github/workflows/dev_main_sync.yml
Fixing source branch in the PR bot
=> Adding the dev branch as source

config/sidebar.config.js, source/docs/casper/dapp-dev-guide/tutorials/index.md, source/docs/casper/dapp-dev-guide/writing-contracts/index.md
[https://casperlabs-team.slack.com/archives/C0135SDEGUC/p1649700128111589](https://casperlabs-team.slack.com/archives/C0135SDEGUC/p1649700128111589)
As per request, I've updated the tutorial table of contents within the [Introduction](https://docs.casperlabs.io/tutorials/) page to include recently added tutorials.
I've also added the relevant tutorials to the [Writing Contracts Index](https://docs.casperlabs.io/writing-contracts/), which may have to be altered in the near-future as we revamp this content.
=> Tutorial Introduction/Table of Contents Update

source/docs/casper/dapp-dev-guide/tutorials/cep47/deploy.md
Missing npm run bootstrap command in tutorial
=> Missing npm run bootstrap command in tutorial

crowdin.yml
Deleting unnecessary crowdin.yml file
=> Removing unnecessary file

.github/workflows/dev_main_sync.yml
In this PR I am including tech writers to the pre-selected reviewers of the automated "Sync to main" PR.
I have also made the request body more explanatory.
=> Bradjohnl add reviewers to sync

config/algolia.config.js, config/analytics.config.js
This PR removes some non-necessary hardcoded values and files.
=> Bradjohnl further cleanup hardcoded stuff

source/docs/casper/dapp-dev-guide/dictionaries.md
No associated ticket, fixing a typo on the dictionary page.
=> Dictionary Typo Fix

.github/workflows/dev_feat_sync.yml
I had to do more fixes as it was still not working as intended.
Also to handle the cases when we don't have any feature branch, the job should not fail, but simply skip the PR creation part.
=> Bradjohnl sync feat branch

source/docs/casper/workflow/verify-transfer.md
N/A
Added a `--node-address` field to [Verify a Transfer - Query the Target Account](https://docs.casperlabs.io/workflow/verify-transfer/#query-the-target-account)
=> Correcting Field Info in a Document

source/docs/casper/design/execution-semantics.md
=> fix typo on execution page

source/docs/casper/workflow/setup-private-network.md
Closes #604
Adds more details about `global-state-update-gen` tool, how to install it, what's the expected output and how to deal with `global_state.toml` files.
Waiting for a debian package with a `global-state-update-gen`
=> Add more details about global state tool.

source/docs/casper/dapp-dev-guide/tutorials/counter/index.md
I noticed that the video had been removed from YouTube, and I am not sure what happened. Before uploading a new video (if we decide to), I think it is best to remove it for now.
=> Remove missing video from the docs

config/sidebar.config.js, source/docs/casper/operators/install-mainnet.md, source/docs/casper/operators/upgrade.md
Card [159](https://github.com/casper-network/docs/issues/159)
Added content to install Mainnet node and upgrade protocol versions.
=> Added node installation and upgrade information

source/docs/casper/workflow/setup.md
Requirements in card https://github.com/casper-network/docs/issues/260.
- Added a very brief description that the faucet can only be invoked once.
=> Add faucet token limitation note

source/docs/casper/workflow/setup.md
N/A Zoom Discussion from Documentation Grooming
Slight formatting issue on the associated page.
Ran locally and confirmed correct.
=> Prereq Page Formatting Fix

source/docs/casper/design/p2p.md
[Incorporate suggested improvements in the Inter-node connections section #637](https://github.com/casper-network/docs/issues/637)
Slight alteration in text as suggested.
=> 637 Slight Text Fix in 'Inter-node Connection' Section

source/docs/casper/dapp-dev-guide/building-dapps/casper-signer.md
None
Fixed wrong link text description 
=> Fixed wrong link text description

source/docs/casper/dapp-dev-guide/building-dapps/casper-signer.md, source/docs/casper/dapp-dev-guide/list-cspr.md
[Developer workflow for integrating staking commands #659](https://github.com/casper-network/docs/issues/659)
Incorporating information provided by @eugenebelov to assist exchanges that want to integrate staking for custodial users. 
=> 659 Exchange Staking Integration

source/docs/casper/dapp-dev-guide/building-dapps/setup-nctl.md, source/docs/casper/dapp-dev-guide/tutorials/counter-testnet/index.md, source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md, source/docs/casper/dapp-dev-guide/writing-contracts/getting-started.md
The video list changed, so we are showing the wrong videos. I found this while reading the docs.
I ran the site locally and tested all 4 videos.
=> Fixed video links in the docs

config/sidebar.config.js, source/docs/casper/design/networking-protocol.md
N/A
Added the Networking Protocol update to the Design page sidebar and altered the top level heading to conform with the other documents in the sidebar.
=> 1.5 Sidebar Update for Network Protocol

source/docs/casper/dapp-dev-guide/writing-contracts/calling-contracts.md
This was a Slack suggestion and discussion with our dev team.
=> Clarify put-deploy --show-arg-examples

config/sidebar.config.js, source/docs/casper/design/highway.md
[Document Highway Consensus Protocol #585](https://github.com/casper-network/docs/issues/585)
High-level description of the Highway Consensus Protocol with information extracted from the whitepaper and previous documentation.
=> 585 Highway Consensus Protocol Documentation

source/docs/casper/dapp-dev-guide/building-dapps/nctl-test.md
"Further, verify that..." indicates an action is required from the reader and thus illustrating the point with a command could be more explicit.
=> Add view user command

source/docs/casper/dapp-dev-guide/writing-contracts/testing-contracts.md
casper-execution-engine has a little update now
=> casper-execution-engine is now 2.0.1

source/docs/casper/dapp-dev-guide/writing-contracts/rust-contracts.md, source/docs/casper/dapp-dev-guide/writing-contracts/testing-contracts.md, source/docs/casper/dapp-dev-guide/writing-contracts/testing-session-code.md
None
I updated the documentation to match the latest counter repository (updated today).
Ran locally without issues.
=> Updated links and code samples 

source/docs/casper/dapp-dev-guide/writing-contracts/dictionaries.md
[Feedback and additional requests for the dictionary page #803](https://github.com/casper-network/docs/issues/803)
Addressed feedback as applicable, 
N/A
=> 803 Incorporating Dictionary Doc Feedback

source/docs/casper/dapp-dev-guide/build-on-casper/index.md
Hello,
We are a Casper node provider NOWNodes. 
Could you update the list of developer tools?
=> Update tools list

.husky/pre-commit, source/docs/casper/dapp-dev-guide/quickstart.md, source/docs/casper/dapp-dev-guide/tutorials/counter-testnet/commands.md, source/docs/casper/dapp-dev-guide/tutorials/counter-testnet/index.md, source/docs/casper/dapp-dev-guide/tutorials/counter-testnet/overview.md, source/docs/casper/dapp-dev-guide/tutorials/counter-testnet/walkthrough.md, source/docs/casper/dapp-dev-guide/tutorials/counter/commands.md, source/docs/casper/dapp-dev-guide/tutorials/counter/index.md, source/docs/casper/dapp-dev-guide/tutorials/counter/overview.md, source/docs/casper/dapp-dev-guide/tutorials/counter/walkthrough.md, source/docs/casper/dapp-dev-guide/writing-contracts/calling-contracts.md, source/docs/casper/dapp-dev-guide/writing-contracts/installing-contracts.md
- Updated counter on an NCTL tutorial with new counter repository details
- Updated counter on the Testnet tutorial with new counter repository details
- Updated "Example - Session code acting on a contract" with new counter contract WASM name
@ACStoneCL @ipopescu
=> Updated counter tutorials and calling contract

source/docs/casper/workflow/operators/setup-private-network.md
See https://github.com/casper-network/docs/issues/930 for details.
=> Fix invalid note syntax

source/docs/casper/developers/cli/transfers/direct-token-transfer.md
Backporting https://github.com/casper-network/docs-new/pull/9 - look there for details.
=> Polish "Direct token transfer" page

.github/pull_request_template.md
Add a reminder to close associated tickets by entering the "Closes #..." line and explanation.
No relevant checks.
@ACStoneCL 
FYI @RitaMAllenCA the docs will include this reminder.
=> Add a shortcut to close associated issues

source/docs/casper/developers/json-rpc/json-rpc-informational.md, source/docs/casper/developers/json-rpc/json-rpc-pos.md, source/docs/casper/developers/json-rpc/json-rpc-transactional.md, source/docs/casper/developers/json-rpc/types_chain.md
[Fix Example Code in the JSON-RPC Docs #973](https://github.com/casper-network/docs/issues/973)
Closes #973 
Replaces all previous code examples with examples drawn directly from an active node's RPC schema.
@darthsiroftardis
=> 973 Correct JSON-RPC API Code Examples

source/docs/casper/developers/dapps/sdk/index.md
Updating the title inside the comments, post PR 966.
=> Update title at the top of the page (post PR 966)

src/assets/scss/_global.scss, src/assets/scss/theme.scss, src/components/atoms/DocsSection/DocsTile/DocsTile.module.scss, src/components/atoms/FeatureSection/FeatureTile/FeatureTile.module.scss, src/components/atoms/ImageAndTextBlock/ImageAndTextBlock.module.scss, src/components/atoms/SocialSection/SocialTile/SocialTile.module.scss, src/theme/DocPage/Layout/Sidebar/index.jsx, src/theme/Footer/ExtendedFooter/ExtendedFooter.module.scss, src/theme/Footer/ExtendedFooter/index.tsx, src/theme/Navbar/ExtendedNavbar/NavBarDropdown/NavBarDropdown.module.scss, src/theme/Navbar/ExtendedNavbar/Search/SearchBox/index.tsx, src/theme/Navbar/ExtendedNavbar/SideBar/SideBar.module.scss, src/theme/Navbar/ExtendedNavbar/index.tsx, src/theme/Navbar/MobileSidebar/Layout/index.jsx, src/theme/Navbar/MobileSidebar/Layout/styles.module.scss
Synchronize recent UI-related changes, starting after https://github.com/MiracleDevs/casper-docs-new/commit/fd3ec8750505520ca81313869be4edc5b0f92a49, up to the latest version  https://github.com/MiracleDevs/casper-docs-new/commit/c89775c1492b13b19c22b76b74549300001f91ab. According to MiracleDevs it should fix navbar on iOS and couple of other minor issues.
This is backport of https://github.com/casper-network/docs-new/pull/194, and you can preview it [live here](https://staging.docs.casper.network/).
=> Theme fixes

CONTRIBUTE.md, README.md
This PR introduces style guides for specific Casper structures and components, as well as a few additional style rules that have evolved over time.
Closes #871 
[Update the contribution.md file #871](https://github.com/casper-network/docs/issues/871)
@ipopescu
=> 871 Updating CONTRIBUTE.md

config/announcement.config.js, docusaurus.config.js
=> Disable DevPortal changes announcement

source/docs/casper/resources/build-on-casper/index.md, source/docs/casper/users/block-explorer.md
=> Add Div3.in explorer

source/docs/casper/resources/build-on-casper/index.md
Add Casper Snap for Metamask Flask as a wallet.
=> Add Casper Snap

source/docs/casper/resources/tutorials/beginner/counter-testnet/commands.md, source/docs/casper/resources/tutorials/beginner/counter-testnet/index.md, source/docs/casper/resources/tutorials/beginner/counter/commands.md, source/docs/casper/resources/tutorials/beginner/counter/index.md
Polishes counter examples under beginner tutorials.
These changes are backported from the default branch of [docs-new](https://github.com/casper-network/docs-new) repository, so you can preview them [live here](https://staging.docs.casper.network/counter-testnet/).
Original PR authored by @jonas089: https://github.com/casper-network/docs-new/pull/135.
=> Polished counter tutorials

package.json, yarn.lock
=> Update Docusaurus to 2.4.0

config/sidebar.config.js, source/docs/casper/dapp-dev-guide/list-auth-keys.md, source/docs/casper/developers/dapps/callstack-based.md, source/docs/casper/developers/dapps/explanation-session-and-contract.md, source/docs/casper/developers/dapps/sdk/additional-libraries.md, source/docs/casper/developers/writing-onchain-code/contracts-and-session-code.md, source/docs/casper/developers/writing-onchain-code/prerequisites.md, source/docs/casper/resources/changelog.md, source/docs/casper/resources/contribute-to-docs.md, source/docs/casper/resources/sample-projects.md, source/docs/casper/resources/support.md
Disable indexing for hidden pages - see https://github.com/casper-network/docs/issues/1071.
=> Disable indexing for hidden pages

source/docs/casper/operators/setup/node-endpoints.md
- Adds content from the support portal and fixed 2 existing commands
- Closes #1040 
@ACStoneCL
=> Operators: add content; fix existing commands

source/docs/casper/developers/cli/installing-contracts.md
Improved [Installing Smart Contracts and Querying Global State](https://docs.casper.network/developers/cli/installing-contracts/), mainly:
- Updated intro, as this is no longer tutorial
- Simplified prerequisites
- Rephrased subsection about state root hash
- Unified command blocks to use 2 spaces as indentation
Closes #1107.
=> Polished "Installing Smart Contracts and Querying Global State"

config/sidebar.config.js, source/docs/casper/operators/index.md, source/docs/casper/operators/setup/non-root-user.md
Added content from the wiki. Tested and edited the content.
Closes #1035 
@ACStoneCL
=> 1035 Add 'non root user' instructions for operators

CONTRIBUTE.md, source/docs/casper/concepts/accounts-and-keys.md, source/docs/casper/developers/cli/calling-contracts.md, source/docs/casper/developers/cli/delegate.md, source/docs/casper/developers/cli/installing-contracts.md, source/docs/casper/developers/cli/transfers/direct-token-transfer.md, source/docs/casper/developers/cli/transfers/multisig-deploy-transfer.md, source/docs/casper/developers/cli/undelegate.md, source/docs/casper/developers/dapps/nctl-test.md, source/docs/casper/developers/dapps/sdk/script-sdk.md, source/docs/casper/developers/writing-onchain-code/writing-session-code.md, source/docs/casper/operators/becoming-a-validator/bonding.md, source/docs/casper/operators/becoming-a-validator/unbonding.md, source/docs/casper/operators/setup-network/create-private.md, source/docs/casper/resources/quick-start.md, source/docs/casper/resources/tutorials/advanced/cross-contract.md, source/docs/casper/resources/tutorials/advanced/list-cspr.md, source/docs/casper/resources/tutorials/advanced/two-party-multi-sig.md, source/docs/casper/resources/tutorials/beginner/counter-testnet/commands.md, source/docs/casper/resources/tutorials/beginner/counter-testnet/walkthrough.md, source/docs/casper/resources/tutorials/beginner/counter/commands.md, source/docs/casper/resources/tutorials/beginner/counter/walkthrough.md, source/docs/casper/resources/tutorials/beginner/upgrade-contract.md
- Added to the contribution guidelines to explain the strategy used here i dealing with hard-coded values
- Made the updates by searching the docs for put-deploy commands
Closes #1140
@ACStoneCL
=> 1140 - Update hard-coded values

source/docs/casper/developers/cli/delegate.md, source/docs/casper/developers/cli/undelegate.md, source/docs/casper/operators/becoming-a-validator/bonding.md
=> 1153 - Use the system auction for delegate and undelegate

source/docs/casper/resources/advanced/multi-sig/multi-sig-workflow.md
I am unsure how this link passed all the link checkers [for the multi-sig PR](https://github.com/casper-network/docs/pull/1228). I found that the link isn't working while trying to update the feat-1.5.0 branch. See commit https://github.com/casper-network/docs/pull/1235/commits/e170b0b0ef3479d33482e6e5c12ad02024751ca8.
=> Fix 404 in multi-sig-workflow.md

source/docs/casper/operators/maintenance/moving-node.md
// Add a brief description or bullet points about the changes introduced. 
// Include an issue number that is associated with this PR.
No bonding is required when wapping the key on servers.
Closes #<enter issue>
// Add further detail on the current situation, or what the PR seeks to address.
// Include [loom](https://www.loom.com/), screenshots, or gifs([record](https://giphy.com/apps/giphycapture), [compress](https://gifcompressor.com/)) if helpful.
Discussed on slack 
https://casper-labs-team.slack.com/archives/CDX4YAHNW/p1698233745459229?thread_ts=1698222868.885679&cid=CDX4YAHNW
// Tag whoever needs to review. If you're not sure, leave blank.
=> remove bond from moving-node

source/docs/casper/developers/cli/calling-contracts.md, source/docs/casper/developers/writing-onchain-code/getting-started.md, source/docs/casper/developers/writing-onchain-code/index.md, source/docs/casper/developers/writing-onchain-code/simple-contract.md
4 videos have been updated and published, and we link to them in the docs:
- Vid 1: https://youtu.be/JoOjhSOnQzk
- Vid 2: https://youtu.be/aIhA5fPIHus
- Vid 6: https://youtu.be/yHJwkhO5EQg
- Vid 14: https://youtu.be/XB_ojY1_0Uo
Closes #1331 
@ACStoneCL
=> Update links to new videos

docusaurus.config.js
Fix CMS GraphQL Query for NavBar 
@bradjohnl
=> NavItems query removed.

config/sidebar.config.js, source/docs/casper/users/csprlive/index.md, source/docs/casper/users/ledger/index.md
There are 2 more fixes needed related to the navigation loop discovered in issue #1344.
I created index pages here, they seemed more appropriate.
@ACStoneCL 
FYI @mrkara
=> 1344 Navigation fix part 2

source/docs/casper/concepts/design/index.md, source/docs/casper/developers/cli/transfers/index.md
A couple of pages needed more descriptive titles. The rest were updated earlier this year.
Closes #1093
@ACStoneCL
=> 1093 - Use more descriptive titles

config/navbar.config.js, source/docs/casper/concepts/economics/staking/delegation.md, source/docs/casper/developers/prerequisites.md, source/docs/casper/operators/becoming-a-validator/recovering.md, source/docs/casper/resources/tokens/cep18/full-tutorial.md, source/docs/casper/users/ledger/ledger-setup.md
As discussed, we are disabling links in the docs for now.
=> Disable links to social temporarily

config/navbar.config.js, source/docs/casper/concepts/economics/staking/delegation.md, source/docs/casper/developers/prerequisites.md, source/docs/casper/operators/becoming-a-validator/recovering.md, source/docs/casper/resources/tokens/cep18/full-tutorial.md, source/docs/casper/users/ledger/ledger-setup.md
Revert the [PR](https://github.com/casper-network/docs/pull/1362/files) that commented out the social links; add the new Discord link.
Closes #1367 
@ACStoneCL or @Jiuhong-casperlabs
=> Updates to use new Discord link

source/docs/casper/resources/beginner/counter-testnet/walkthrough.md
- note on the node address format and the importance of using the port `7777`
- wrong path in one of the commands
- formatting
=> Testnet counter walkthrough

source/docs/casper/resources/advanced/cross-contract.md
- Fix project directory tree
- Change \```bash to \```rust in aplicable places
- Rephrase some of the content
- Fix formatting
=> Cross-contract tutorial updates

source/docs/casper/developers/prerequisites.md, source/docs/casper/resources/casper-open-source-software.md, source/docs/casper/resources/quick-start.md, source/docs/casper/resources/tokens/cep78/introduction.md, source/docs/casper/resources/tokens/cep78/reverse-lookup.md, source/docs/casper/resources/tokens/cep78/using-casper-client/interacting-with-NFTs.md
Add a note regarding token_hash during minting if the identifier mode is set to hash.
=> Note regarding token_hash when minting NFTs

source/docs/casper/developers/json-rpc/json-rpc-informational.md, source/docs/casper/developers/json-rpc/types_chain.md, source/docs/casper/resources/tokens/cep78/introduction.md, source/docs/casper/resources/tokens/cep78/reverse-lookup.md
This PR updates the JSON-RPC API documentation to align with recent changes on the `feat-2.0` branch of `casper-node`
@ipopescu
=> Updating JSON-RPC Docs

source/docs/casper/operators/setup-network/create-private.md
A link was updated. The main branch was renamed to dev:
https://github.com/casper-ecosystem/casper-client-rs/blob/dev/README.md#casper-client
=> Fixing the build

source/docs/casper/operators/setup-network/create-private.md
Duplicating [Iulia's `dev` fix](https://github.com/casper-network/docs/pull/1432).
=> Fixing `feat-2.0` Build

source/docs/casper/developers/prerequisites.md
Clarify that we don't support macOS, but we document the equivalent commands for developers who wish to use a Mac.
=> Clarify macOS commands & support

source/docs/casper/operators/becoming-a-validator/bonding.md
Minimum/maximum delegation amount optional arguments for `add_bid` contract introduced in v2.0.
=> Describe minimum/maximum delegation amount
