- source/docs/casper/dapp-dev-guide/execution-error-codes.md
A very small update to the link from "mappings" to "variants".
> Fix link to https://docs.rs/casper-types

- source/docs/casper/dapp-dev-guide/getting-started.md
rustup install nightly instructions contained an extra cd that was unncessary
> Remove extra cd command from install instructions

- README.md
https://github.com/casper-network/docs/issues/126
Added section under "Troubleshooting" describing the recommende workaround to the issue to be used before we start using Docusaurus v2.0.0-beta9.
None.
> Updating README with troubleshooting instructions

- .github/workflows/main.yml
- .gitignore
N/A
First setup of a Github Action setup to automatically build and deploy to the Github Pages site (CI/CD). 
The deployment happens only on pushes to the main branch (pull requests merges counts as such).
For the moment, it will deploy to the site: https://casper-network.github.io/ and will not affect the current prod.
After, if everything works correctly, the casper.network/docs site will need to point to casper-network.github.io/docs.
This might lead to other small changes.
In the previous unmerged version there was a "test-deploy" phase in which  there were system tests on AWS LocalStack which had to pass before deploying to prod. Those, will be implemented in subsequent pull requests using Jekyll most probably. (See https://github.com/bradjohnl/docs/blob/bradjohnl-cicd_aws_ghactions/. …
> GitHub Pages CI/CD

- source/docs/casper/workflow/signer-guide.md
I noticed that this section was not formatted well:
I've updated it to look like this:
> Fix formatting for password requirements in Signer Guide

- .github/workflows/main.yml
https://stackoverflow.com/a/58655352
I noticed that the GitHub Actions pipeline was not being triggered when the pull request was created using a fork. This pull request allows it.
Also the templating of the .env.production files has been set up to be executed only when on the main branch as that file is needed only if you are about to deploy to prod.
As I noticed that sometimes pull requests are created to non-main branches, I changed the workflow to run on pull-requests with any branch as target.
It's good to be able to check the build status when a pull request gets created. The reviewer does not have to check the fork where it comes from and already knows that he/she should not check it if the workflow is not successful.
The reviewer should also not trust the build action results of a …
> Bradjohnl cicd on pull request too

- .github/workflows/main.yml
Post-deployment tests are performed and the previous version of the site is deployed in case of failures
Tests can be expanded with more functionality.
The same strategy will be used in a planned feature where the GitHub pages site is first deployed locally by the runner.
> Implementation of Prod tests post deployment with rollback if one fails

- .github/workflows/main.yml
This change prevents Github Actions from uploading the deployment artifact when no deployment is going to be made based on existing conditions.
> The deployment artifact should be uploaded only if a deployment is expected

- .github/workflows/main.yml
- https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll
- https://pages.github.com/versions/
- https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll
- https://github.community/t/use-working-directory-for-entire-job/16747/2
- https://docusaurus.io/docs/api/docusaurus-config#baseurl
- https://docs.knapsackpro.com/2021/how-to-load-ruby-gems-from-cache-on-github-actions
- https://github.com/ruby/setup-ruby
These changes implement system tests which run on a local Github pages website identical to the one resulting from the current build. If the tests are not successfull, the pipeline will fail and the deployment will be stopped.
For non-main branches the …
> Bradjohnl test before depl

- source/docs/casper/dapp-dev-guide/testing.md
Requirement card: https://github.com/casper-network/docs/issues/167
I corrected this command:
builder.exec(execute_request).commit().expect_success();
And replaced it with:
builder.exec(execute_request).expect_success().commit();
Ran the site locally.
> Updated commit command

- README.md
- source/README.md
Requirements card: https://github.com/casper-network/docs/issues/183
- Updated the main README file:
- removed references to the docs-app directory (the old name)
- the source/docs/casper directory is already mentioned, so I pointed to the next section
- specified Node version 14+ (instead of npm version 14); npm comes with the Node.js installation
- Removed an old README file in another directory
I ran the site locally as well, even though the readme changes shouldn't have had any impact.
I cannot see any precomit hooks failing, but I reached out to the team to follow up on it.
> Updated readme file

- source/docs/casper/dapp-dev-guide/getting-started.md
- source/docs/casper/dapp-dev-guide/setup-nctl.md
Requirements: https://github.com/casper-network/docs/issues/185
**Getting Started updates:**
- I updated the docs language in the “Test the Contract” section . It used to read:  “Since the test script automatically builds the contract, during development you only need to run the command make test without the need for “cargo build”.” However, we are no longer telling them to issue cargo build commands.
**NCTL guide updates:**
- The command “nctl-compile” takes well over 1 hour to compile everything. Added a note in the docs to go get coffee. I am not sure if this is in accordance with our style guide, but I wanted to let the reader know to expect a delay. @GloreenS and @Buddhika-Pathirathna, what do you think?
- Reply by Buddhika - @ipopescu - I think it's cool - audience-friendly - but …
> Minor updates to the `getting started` and `nctl` guides

- source/docs/casper/dapp-dev-guide/sdk/index.md
Requirement Card:
[Add info about Casper SDKs #106](https://github.com/casper-network/docs/issues/106)
Added several additional SDKs as requested, as well as adding a 'Maintainer' column with available contact information.
Ran locally with no issues.
> Updating Casper SDK Information

- config/sidebar.config.js
- source/docs/casper/dapp-dev-guide/why-build-on-casper.md
- source/docs/casper/index.md
Card #71 
Changes:
Casper Network Document Landing Page: 
- Removed the section, "Why Choose Casper" and added relevant contents to the "Why-Build-on-Casper" page.  
-The newly designed page for "Why-Build-on-Casper" has been linked to the landing page - in the third paragraph under "What is Casper?" 
Link: https://casper.network/docs/.  (ref. as landing page later)
Why-Build-on-Casper Page: 
- Content adopted as per Card #71 
- Changes made in Rust and Web Assembly Section - Header updated to reflect new contents taken from the landing page.
- Changes made to Advanced Account Management, Contract Upgrades and Low Gas fee sections to add new information, updated to select contents from the landing page . 
> New page added

- source/docs/casper/faq/faq-developer.md
- source/docs/casper/faq/faq-enterpise.md
- source/docs/casper/faq/faq-general.md
- source/docs/casper/faq/faq-validator.md
Requirement cards:
[Move SRE FAQ to the docs #76](https://github.com/casper-network/docs/issues/76)
[Smart contracts cannot talk to the outside world #107](https://github.com/casper-network/docs/issues/107)
I've added the information from the prior Atlassian SRE FAQ to the current documentation FAQs. This included changes to both the developer and validator FAQs.
Also included is the change requested in docs #107.
Both pages ran locally without issue.
> Integrating Atlassian SRE FAQ

- source/docs/casper/dapp-dev-guide/tutorials/counter/index.md
- source/docs/casper/dapp-dev-guide/tutorials/multi-sig/index.md
- source/docs/casper/workflow/staking.md
No corresponding link or card; requirement coming from internal discussions.
- I commented out the videos that I know need to be updated:
- The counter tutorial
- The multi-sig tutorial
- The staking tutorial
- The corresponding write-ups have been updated, but the videos need more time for editing.
- We have separate cards in our backlog for updating the videos.
> Remove old videos

- config/sidebar.config.js
- source/docs/casper/staking/index.md
- source/docs/casper/workflow/block-explorer.md
- source/docs/casper/workflow/deploy-transfer.md
- source/docs/casper/workflow/index.md
- source/docs/casper/workflow/ledger-setup.md
- source/docs/casper/workflow/signer-guide.md
- source/docs/casper/workflow/staking.md
- source/docs/casper/workflow/testnet-faucet.md
- source/docs/casper/workflow/token-transfer.md
Card #136 and #138 
- Reworded references to cspr.live
- Updated capitalization of commonly used terms to be consistent with other topics
- Split topic "Transferring Tokens on the Casper Testnet" to generalize transfer instructions and created separate topic for testnet faucet feature "Funding Testnet Accounts"
- Updated references to UI elements in Transferring Tokens to match the actual UI
- Added references to the signer guide and removed steps repeated from the signer guide
- Added a new topic for block explorers
- Updated references of block explorers to point to the block explorers topic
Testnet is available only on the cspr.live block explorer, so added a separate reference to this in the Funding Testnet Accounts topic.
> Generalize cspr.live references

- config/sidebar.config.js
- source/docs/casper/dapp-dev-guide/understanding-hash-types.md
[Document different hashes #68]{https://github.com/casper-network/docs/issues/68}
I reviewed, edited, formatted, and integrated the [information provided by devs](https://app.zenhub.com/files/165094962/84ef82a3-889b-4a64-ad52-7d61275414ad/download) by creating a new page titled 'Understanding Hash Types' within the Developers section of the documentation.
Page ran locally without issue - verified sidebar inclusion.
> 68 Integrating hash type documentation

- source/docs/casper/dapp-dev-guide/deploying-contracts.md
- source/docs/casper/dapp-dev-guide/tutorials/counter/setup.md
- source/docs/casper/operators/setup.md
- source/docs/casper/workflow/setup.md
[Consolidate Casper client instructions #195](https://github.com/casper-network/docs/issues/195)
I've consolidated instructions from the two listed pages [Prerequisites](https://casper.network/docs/workflow/setup#the-casper-command-line-client) and [Deploying Contracts](https://casper.network/docs/dapp-dev-guide/deploying-contracts#the-casper-client) to include all necessary information. I also made slight wording changes to bring the document more in line with the Writing Style Guide
I then removed redundant instructions and replaced them with a link to the [Prerequisites](https://casper.network/docs/workflow/setup#the-casper-command-line-client) on the following pages:
[Developers - Deploying Contracts](https://casper.network/docs/dapp-dev-guide/deploying-contracts)
[Developers - …
> 195 Consolidate Casper client instructions

- source/docs/casper/dapp-dev-guide/getting-started.md
[Extend the mentioned list of wasm compatible languages #99](https://github.com/casper-network/docs/issues/99)
Added a note about languages other than Rust that are compatible with WASM.
I went through the documentation and looked for other instances where this note would be applicable - but this is the only document that has that degree of specificity.
Page ran locally without issue.
> 99 Including info about additional languages

- source/docs/casper/dapp-dev-guide/deploying-contracts.md
- source/docs/casper/dapp-dev-guide/keys.md
- source/docs/casper/dapp-dev-guide/sdk/csharp-sdk.md
- source/docs/casper/dapp-dev-guide/tutorials/erc20/tests.md
- source/docs/casper/design/serialization-standard.md
- source/docs/casper/economics/delegation.md
- source/docs/casper/faq/faq-developer.md
- source/docs/casper/faq/faq-validator.md
- source/docs/casper/operators/index.md
[28 infra integrate markdown link checkin #220](https://github.com/casper-network/docs/pull/220)
I went through and updated broken or incorrect links that showed up in the new external link checker created by @sd-ditoy
I did not change any links within the /i18n/ directory, as it does not appear up to date and likely requires further changes before maintenance.
All changes ran locally and new links were checked for validity.
> 28 Fixing broken and inaccurate links

- source/docs/casper/faq/faq-general.md
[Explain account-hash vs account-hex #90](https://github.com/casper-network/docs/issues/90)
Added the associated question to the General FAQ.
Page ran locally without issue.
> 90 Adding account hash vs hex question to FAQ

- source/docs/casper/faq/faq-developer.md
- src/utils/docs.js
Did not found a related issue.
URL of the docs repository is corrected  in `src/utils/docs.js`.
> Fix 'Edit this page' link

- config/sidebar.config.js
- source/docs/casper/workflow/contribute.md
[Move the Style Guide to a CONTRIBUTE.md file #216](https://github.com/casper-network/docs/issues/216)
I've reproduced the Confluence style guide in a markdown file and added it to the 'How To's'/Workflow section of the Docs.
Page ran locally without issue.
> 216 Importing the Style Guide from Confluence

- source/docs/casper/dapp-dev-guide/tutorials/counter/index.md
Backlog://github.com/casper-network/Governance/issues/188.
- Updated content for the counter tutorial to use the Testnet instead of NCTL
- Updated video, which has been uploaded to YouTube (Module 4 - Application, index=6)
> Publish the latest counter video

- source/docs/casper/workflow/erc20-token-deployment-guide.md
Removed unneeded prerequisites and the "public_key.pem" requirement in the KEYS constant (As the signer no longer downloads the public key when backing-up accounts).
> Removed unneeded prereqs, removed public key file req

- source/docs/casper/workflow/erc20-token-deployment-guide.md
https://github.com/casper-network/docs/pull/276
https://github.com/casper-network/docs/pull/272
Fixed the following issues:
• Keys.Ed25519.parseKeyFiles() does not work only with the secret key. Keys.Ed25519.loadKeyPairFromPrivateFile()can.
• The repo casper-erc20-js-interface has not been updated. Now there's a mismatch between the code in the README and the code in the repo.
• To follow this tutorial someone doesn't need to have rust or casper-client. I'd remove this: Set up your machine as per the prerequisites.
> Fix for issue 276/272

- source/docs/casper/operators/joining.md
Created a separate sub-section and clarified that the default in config.toml point to mainnet.
> Clarified known_addresses section

- config/sidebar.config.js
- source/docs/casper/dapp-dev-guide/tutorials/transfer-token-to-contract.md
[Tutorial for how to safely transfer token to a contract #274](https://github.com/casper-network/docs/issues/274)
[Documentation on how-to-use purses in a smart contract #286](https://github.com/casper-network/docs/issues/286)
Added a "Safely Transferring Tokens to a Contract" tutorial, within the [Developers](https://casper.network/docs/dapp-dev-guide/) section under tutorials.
Page ran locally without issue.
Tagged the tech writing team for proofreading/editting and Ed for review of content.
> 274 Tutorial for transferring tokens to a contract

- .github/workflows/main.yml
I found out an issue that causes the custom domain setting to be removed from the GitHub Pages site at every deployment, causing the site to revert back to the [github.io](http://github.io/) domain. 
When this happens the site does not work.
It is because the CNAME file that is necessary for Github to use the [docs.casperlabs.io](http://docs.casperlabs.io/) domain does not get automatically pushed to the gh-pages branch at every deployment.
This PR fixes this issue.
> Bradjohnl fix cname generation

- source/docs/casper/workflow/erc-20-sample-guide/index.md
- source/docs/casper/workflow/erc20-token-deployment-guide.md
Card - [318](https://github.com/casper-network/docs/issues/318)
Updated the existing links to the new ERC-20 tutorial location.
-
> Updated the links to erc-20 tutorial

- source/docs/casper/dapp-dev-guide/tutorials/kv-storage-tutorial.md
- add \ for multiline commands
- use single quote for argument values vs `
- store-string function name should be store_string
- add the missing value argument
Existing calls do not work
Also note that the corresponding sample is broken generally - https://github.com/casper-ecosystem/kv-storage-contract/issues/13
> put_deploy call fixes

- source/docs/casper/dapp-dev-guide/on-chain-contracts.md
[Explain the deploy payment in more detail #84](https://github.com/casper-network/docs/issues/84)
Due to the changed file name and previous discussion from [84 deploy payment info #229](https://github.com/casper-network/docs/pull/229), I am creating a new PR to point to the new document. This includes the Deploy Payment description, with any example code to be included later through an additional card.
Previous PR closed due to various incongruities as documents evolved.
> 84a Updated Deploy Payment PR

- source/docs/casper/design/serialization-standard.md
[Create SDK Specification - Serialisation & Info #265](https://github.com/casper-network/docs/issues/265)
Updating the Serialization Standard to include all types, in tandem with [docs#266](https://github.com/casper-network/docs/issues/266)
> 265 Serialization Update

- .github/workflows/dev_main_sync.yml
The current strategy used is not working to successfully submit the PR to sync dev to main.
This is using another approach.
> Changing PR bot strategy

- source/docs/casper/dapp-dev-guide/sdk/index.md
https://docs.casperlabs.io/sdk/
https://github.com/casper-network/docs/blob/dev/source/docs/casper/dapp-dev-guide/sdk/index.md
Removes Erlang from list of Casper SDKs
> Remove Erlang SDK

- config/sidebar.config.js
With PR #348 we deleted the index page:
Adding it back:
> Add back the tutorials index page

- .github/workflows/dev_main_sync.yml
Adding the hash to the tretuna/sync-branches action too.
> Use commit hash also for the tretuna/sync-branches action

- .github/CODEOWNERS
No related card.
Adding ACStoneCL as a code owner for code reviews.
> Add ACStoneCL as code owner

- source/docs/casper/dapp-dev-guide/writing-contracts/testing-session-code.md
- Adding a minor change related to [415](https://github.com/casper-network/docs/pull/415)
- Related cards - https://github.com/casper-network/docs/issues/330 and https://github.com/casper-network/docs/issues/331
- Added a new link to the 'writing session code' section
> Adding the correct link for writing session code

- source/docs/casper/dapp-dev-guide/writing-contracts/assembly-script.md
- source/docs/casper/dapp-dev-guide/writing-contracts/index.md
[Rust vs AssemblyScript Getting started sections are inconsistent #361](https://github.com/casper-network/docs/issues/361)
I've rearranged the AssemblyScript page in Writing Contracts so that it better matches the 'Getting Started with Rust' page. Content remains mostly the same, with small blurb added about installing AssemblyScript to bring it in line.
> 361 Getting Started Inconsistencies, Rust vs AS

- source/docs/casper/dapp-dev-guide/sdkspec/json-rpc-transactional.md
[#383](https://github.com/casper-network/docs/issues/383)
Added known nodes note to JSON RPC Transactional Methods document.
This addition was made for those who are building Casper SDKs and need reliable nodes to push deploys to.
> Added known node note to JSON RPC transaction documentation

- docusaurus.config.js
- source/docs/casper/index.md
- source/docs/casper/staking/index.md
I have configured Algolia indexer and crawler to take docusaurus tags into consideration.
I tested the Algolia search locally and could see already a great improvement, with search results being presented in a much more visually pleasing way, with the results divided by headers for example.
To test and confirm the behaviour with tags, I need to update the prod site and have the crawler get the pages with the tags. For this reason I have added some tags to 2 pages.
For the future, I will create a ticket to investigate ways to test Algolia search locally with custom crawlers probably.
For the time being, the indexed content will be what is in the prod site only.
NOTE: It has been confirmed by Algolia that the attributes "indexName", "appId", and "apiKey" are safe to commit. 
The apiKey, is …
> Bradjohnl gh 416 algolia docsearch

- config/navbar.config.js
[Issue 560](https://github.com/casper-network/docs/issues/560)
The current discord invite link is no longer valid. Due to the way that discord is engineered as a desktop browser, the link will return as valid as it still points to a discord landing page that then redirects to the discord app. The updated link is the same invite link utilized on casperlabs.io community page, found [here](https://casperlabs.io/community).
> Update discord server invite

- source/docs/casper/faq/faq-developer.md
[Developer FAQ](https://docs.casperlabs.io/faq/faq-developer/)
Noticed a broken link when looking through FAQs.
> Fixing broken hyperlink to another doc in the 'out of gas' FAQ question.

- source/docs/casper/dapp-dev-guide/sdkspec/json-rpc-informational.md
N/A
Updating information on `chain_get_block` to include the 1.5 possibility of a node lacking information on a specific block.
> Update chain_get_block for 1.5

- source/docs/casper/workflow/setup-private-network.md
https://github.com/casper-network/docs/blob/dev/source/docs/casper/workflow/setup-private-network.md
Change description and code of set_action_thresholds.wasm
disable:
```
--session-arg "key_management_threshold:u8='255'" \
--session-arg "deploy_threshold:u8='255'"
```
enable:
```
--session-arg "key_management_threshold:u8='0'" \
--session-arg "deploy_threshold:u8='1'"
```
> fix set_action_thresholds usage

- source/docs/casper/dapp-dev-guide/sdkspec/json-rpc-informational.md
N/A, discussion during standup.
Removing `query_balance` information that unexpectedly showed up on the main site.
> Removing query balance from main

- source/docs/casper/dapp-dev-guide/why-build-on-casper.md
- source/docs/casper/workflow/block-explorer.md
I have recently learned about https://casper-trench.vercel.app/, and I thought we should mention it in our docs. 
Updated the list of block explorers to include the link above.
Ran locally successfully.
> Mention Casper.info as a block explorer

- source/docs/casper/dapp-dev-guide/writing-contracts/index.md
- source/docs/casper/dapp-dev-guide/writing-contracts/testing-session-code.md
[Resolve formatting issue and update the index page #649](https://github.com/casper-network/docs/issues/649)
Fixing formatting issues with the Testing Session Code doc and updating the Writing On-Chain Code Index.
Ran locally without issue and verified correct formatting.
> 649 Formatting and Index Update

- source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
[Non buffering on curl statements for events #515](https://github.com/casper-network/docs/issues/515)
Changed instances of `curl -s` to `curl -sN` as suggested by Joe.
> 515 Fixing Curls for Monitoring Events

- source/docs/casper/glossary/R.md
- source/docs/casper/glossary/S.md
No related card. We realized that based on a [slack conversation](https://casperlabs-team.slack.com/archives/CDXBCHB6W/p1661435588982079) the definition of the root hash was incorrect.
- Updated the definition of the **root hash** in our glossary.
- Also added details for the **state root hash** in the glossary.
- Site ran locally successfully
> State root hash and root hash in the glossary

- source/docs/casper/workflow/setup-private-network.md
Needs to wait until casper-network/casper-node#3291 is merged
Follow up for casper-network/casper-node#3268
Adds a section about how to configure a network access control to restrict unapproved nodes from joining.
> Add section about network identity.

- source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
No related card. This video was created for training and it seemed like a good idea to add it.
- Added a link to the upgrade video tutorial on the upgrade tutorial page.
- Ran the site locally, successfully.
> Upgrade video tutorial in the docs

- source/docs/casper/operators/hardware.md
Resolves https://github.com/casper-network/docs/issues/700
Removed the mention of Ubuntu 18.04 from the Operator Hardware [System Requirements](https://docs.casperlabs.io/operators/hardware/#system-requirements) documentation section
> Remove Ubuntu 18.04 from OS Requirement

- config/sidebar.config.js
- source/docs/casper/dapp-dev-guide/building-dapps/calling-contracts.md
[Calling contracts using Rust code #393](https://github.com/casper-network/docs/issues/393)
Added a document to the Building dApps section that outlines the various deploy variants and their uses.
> 393 Calling Contracts using ExecutableDeployItem

- source/docs/casper/faq/faq-validator.md
- source/docs/casper/operators/setup.md
Resolves #715 
- Updated to Ubuntu 20.04 in this statement _`casper-node` - The node executable - defaults to the Ubuntu 20.04 compatible binary_ in [/var/lib/casper/](https://docs.casperlabs.io/operators/setup/#varlibcasper) section
- Removed Ubuntu 18.04 reference in the [FAQ](https://docs.casperlabs.io/faq/faq-validator/#casper-compatibility) section 
NA
> Remove Ubuntu 18.04 references

- source/docs/casper/dapp-dev-guide/writing-contracts/rust.md
- source/docs/casper/glossary/E.md
- source/docs/casper/glossary/N.md
- #92 
- I added details about named keys in the rust.md file where we describe a simple smart contract. The named keys should be defined before creating the contract with the new_contract function, so I swapped the two sections. Also, I updated the sample code to take in named keys, just for demonstration purposes.
- I added named keys and entry points in the glossary
Ran the site locally without issues.
> 92 Add details regarding named keys and entry points

- source/docs/casper/workflow/setup-private-network.md
This is an issue of certificate expired in one month by default setting on private network chengdu chain.
Original issue on slack
https://casperlabs-team.slack.com/archives/CDX4YAHNW/p1669000277010549
set the expiry days 3650 to node_1_cert.pem
openssl x509 -req -days 3650 -CA ca_cert.pem -CAkey ca_key.pem -CAcreateserial -in node_1.csr -out node_1_cert.pem
> Fix setup private network

- source/docs/casper/economics/gas-concepts.md
[Correct Gas Limit Reasoning within the Economics Docs #787](https://github.com/casper-network/docs/issues/787)
Added the requested terminology shift.
N/A
> 787 Gas Limit Reasoning

- docusaurus.config.js
While trying to fix something else, I found a way to show the "last updated time" on our documentation pages. I remember this was an ask coming from @caspersteve a while back.
I ran the site locally, and I got an auto-generated timestamp.
I expect that the time will be computed for the livesite, and it will look like it does at the bottom of this page: https://docusaurus.io/docs/create-doc.
> Show last updated time in docs

- source/docs/casper/workflow/setup-private-network.md
Client was moved to separate repository, since casper-node v1.4.5.
> Fix invalid casper-client URL

- source/docs/casper/workflow/setup.md
Wrong URL was used for YouTube embedding:
> Fix YouTube iframe URL

- source/docs/casper/dapp-dev-guide/building-dapps/sdk/csharp-sdk.md
- source/docs/casper/dapp-dev-guide/building-dapps/sdk/go-sdk.md
- source/docs/casper/dapp-dev-guide/building-dapps/sdk/script-sdk.md
- #818 and [Slack](https://casperlabs-team.slack.com/archives/C0135SDEGUC/p1672854310891859?thread_ts=1672266383.159399&cid=C0135SDEGUC)
- This PR removes the "/rpc" instances from the sample code; it is unnecessary.
- Site ran locally
> 818 Remove /rpc from examples using port 7777

- source/docs/casper/workflow/deploy-transfer.md
- source/docs/casper/workflow/index.md
- source/docs/casper/workflow/transfers.md
- source/docs/casper/workflow/two-party-multi-sig.md
- source/docs/casper/workflow/verify-transfer.md
- #703 
I ran through the following workflows and improved the flow and instructions. The "minor updates" became more extensive, but the technical content remained the same.
- https://docs.casperlabs.io/workflow/two-party-multi-sig/ - link to the repo and remove code that is copy/pasted
- https://docs.casperlabs.io/workflow/deploy-transfer/ - the most important change here is to mention the two-party-multi-sig as a prerequisite
- https://docs.casperlabs.io/workflow/verify-transfer/ - simplified prerequisites and node-address explanation
The other changes mentioned in card #703 were addressed in a previous PR.
- Ran locally
- @ACStoneCL
- only FYI @darthsiroftardis
> Multi-sig transfer updates

- source/docs/casper/dapp-dev-guide/writing-contracts/session-code.md
- #813 
- Added examples of session code invoking the transfer_* system functions, which are Wasm-based transfers, instead of invoking the native transfer using the RPC endpoint and the casper-client.
- Ran locally
- @ACStoneCL
- @deuszex or @darthsiroftardis
> 813 session code transfers

- source/docs/casper/dapp-dev-guide/writing-contracts/calling-contracts.md
- #801 
- Added examples that use the system auction contract and its `delegate` entry point wherever possible
- I kept the previous examples using the counter contract as well because they tie into the previous sections and videos
- Also, I wasn't able to use the system auction to demonstrate a put-deploy using  `--session-package-name`, so for this, I kept the counter and the erc20_test_call examples
- Added example values in the casper-client put-deploy command (since they are supposed to be examples)
- Editing and flow improvements
- Used rust highlighting (instead of bash) 
- Site ran locally
- I kept only a couple of links to the Counter Tutorial, which needs to be reviewed and use the new counter code
- As I started working on this, I also created PR #823
> 801 Use "delegate" examples in calling-contracts

- source/docs/casper/dapp-dev-guide/building-dapps/casper-signer.md
none
Fixed a typo in a hyperlink to ViteJS
none
> fix typo in casper-signer docs

- source/docs/casper/dapp-dev-guide/building-dapps/sdk/index.md
[Add disclaimer info to SDK listing #853](https://github.com/casper-network/docs/issues/853)
[Change "Maintainer" to "Organization" #852](https://github.com/casper-network/docs/issues/852)
Added the listed disclaimer and changed "Maintainer" to "Organization" as requested. Links changed to reflect the organization hosting the SDKs in question rather than the maintainer specifically.
> 852/853 SDK Disclaimer & Change of Maintainer List to Organization

- source/docs/casper/workflow/setup-private-network.md
[document how to customize/brand the block explorer for a private or hybrid network #837](https://github.com/casper-network/docs/issues/837)
Adding a link to the [block explorer repo](https://github.com/casper-network/casper-blockexplorer) and associated README for private/hybrid chains.
Also added an organizational TOC at the beginning to make the block explorer bit more visible on first look.
> 837 Adding Block Explorer Link to 'Setup a Private Network' doc

- source/docs/casper/dapp-dev-guide/keys.md
- source/docs/casper/design/casper-design.md
- #646 
- Updated [design](https://docs.casperlabs.io/design/casper-design/#accounts-head) and [keys](https://docs.casperlabs.io/dapp-dev-guide/keys/) pages as requested in the ticket
- Ran the docs site locally
- Since the technical details are clear, I am just adding @ACStoneCL as reviewer
> 646 - Add info on why the TrieStore uses account hashes

- source/docs/casper/dapp-dev-guide/building-dapps/casper-signer.md
- source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
- source/docs/casper/dapp-dev-guide/building-dapps/sdk/python-sdk.md
- source/docs/casper/dapp-dev-guide/building-dapps/sdk/script-sdk.md
- source/docs/casper/dapp-dev-guide/setup.md
- source/docs/casper/dapp-dev-guide/understanding-hash-types.md
- source/docs/casper/dapp-dev-guide/writing-contracts/getting-started.md
- source/docs/casper/dapp-dev-guide/writing-contracts/testing-contracts.md
- source/docs/casper/design/casper-design.md
- source/docs/casper/faq/faq-developer.md
- source/docs/casper/faq/faq-general.md
- source/docs/casper/glossary/A.md
- source/docs/casper/glossary/D.md
- source/docs/casper/glossary/R.md
- source/docs/casper/staking/index.md
- source/docs/casper/workflow/delegate.md
- source/docs/casper/workflow/ledger-setup.md
- source/docs/casper/workflow/two-party-multi-sig.md
- Card #404 
* Replaced **commission** with **delegation rate** as appropriate 
* Removed **in-memory** from all virtual machine references, except in the i18 translated files
* I fixed some incorrect comments in the SDK sample code
* Reviewed and updated "**account hash**" usage vs "**account address**"
* No updates to the obsolete multi-sig tutorial
* No updates to the disclaimer. If we need to update this, please let me know. 
> "The` Recipient understands and accepts that CSPR, if and when created and/or issued, will only be accessed by using a wallet technically compatible with CSPR and with a combination of the Recipient’s account information (address) and private key, seed or password. The Recipient understands and accepts that if its private key or password gets lost or stolen, …
> 404 - Terminology updates part 2: delegation rate, account hash usage

- source/docs/casper/dapp-dev-guide/sdkspec/types_cl.md
- source/docs/casper/dapp-dev-guide/setup.md
I am using custom tool to process all the links in docs, and I detected:
- 1 invalid reference,
- 1 external link with trailing space.
This PR fixes them.
> Fix invalid links

- source/docs/casper/dapp-dev-guide/build-on-casper/casper-open-source-software.md
Point the Java SDK link to https://github.com/casper-network/casper-java-sdk, the official and active repository.
> Update link to the Java SDK

- source/docs/casper/dapp-dev-guide/sdkspec/json-rpc-transactional.md
Speculative_Exec is a 1.5 endpoint and should only be on the feat-1.5 branch.
This PR removes the speculative_exec endpoint from the SDK Spec.
@darthsiroftardis
> Remove Speculative_Exec from Current Docs

- source/docs/casper/dapp-dev-guide/building-dapps/sdk/index.md
Removing an old Java SDK link from the list.
I also updated the capitalization to match GitHub repositories.
Does not apply for a simple link deletion.
@ACStoneCL
> Remove old Java SDK link

- config/sidebar.config.js
- source/docs/casper/dapp-dev-guide/list-cspr.md
- source/docs/casper/dapp-dev-guide/sdkspec/types_chain.md
- source/docs/casper/design/serialization-standard.md
- source/docs/casper/workflow/developers/delegate.md
- source/docs/casper/workflow/developers/redelegate.md
- A new workflow for redelegating tokens to a new validator.
- We have a new entry point called `redelegate` in the Auction system contract, which allows users to redelegate to another validator without having to unbond. The function signature for the entry point is: `redelegate(delegator: PublicKey, validator: PublicKey, amount: U512, new_validator: PublicKey)`.
- The [old redelegate.md](https://github.com/casper-network/docs/files/10688916/redelegate-old.md) file from branch feat-1.5.0 is attached. I removed the verification section as it was duplicated (exact copy/paste). I pointed to the `delegate.md` verification steps instead. I also did a complete refresh of this file to match the current format of the `delegate.md` file.
- As part of this, I noticed duplicated content in the …
> 862 - Redelegate documentation

- source/docs/casper/workflow/ledger-setup.md
- Adds ledger-setup.md to the old location as hidden, until Ledger support updates the link on [their site](https://support.ledger.com/hc/en-us/articles/4416379141009-Casper-CSPR-?support=true). Support ticket number 907121. I've also added a TODO in the file that needs to be removed after the link is updated.
- @ACStoneCL
- @bradjohnl as optional
> Add ledger-setup.md to the old location as hidden

- docusaurus.config.js
- package.json
- yarn.lock
Docusaurus packages are bumped to the latest available version **2.3.1**.
I went through **all** release notes for new versions - starting at 2.0.0-beta.17 - and I found 2 breaking changes that applies in our case :boom::
- (2.0.0-beta.19) [sidebar config change](https://github.com/facebook/docusaurus/pull/7277) - updated in this PR,
- ~~(2.0.0-beta.21) [bumped nodejs requirement](https://github.com/facebook/docusaurus/pull/7501) - will be solved when https://github.com/casper-network/docs/pull/949 is merged.~~
> Upgrade Docusaurus to 2.3.1

- check-external-urls.js
This PR fixes an error that sometimes occurs in script that checks external links - https://github.com/casper-network/docs/issues/953.
When `page.goto()` fails within `try..catch` block (it means page was not opened), then `page.close()` should not be called.
> External links checking - skip closing page when goto() failed

- config/sidebar.config.js
- source/docs/casper/operators/setup-network/create-private.md
- source/docs/casper/operators/setup/install-node.md
- source/docs/casper/operators/setup/node-endpoints.md
- source/docs/casper/operators/setup/port-settings.md
Adding more details about a node's ports as requested in card #463 
In response to the requirements written by @devendran-m, I am adding a few notes:
1. the individual ports used by a node operator should be aware of: 35000, 7777, 8888, 9999
2. purpose and significance of each port in a node operation: addressed in this PR
3. the ports that are open by default: I pointed this out in this PR
4. what will happen if a port or ports are closed: addressed in this PR
5. how to leave the ports open and why it is important to leave them open: addressed in this PR
6. how to securely block them from external users/traffic: not addressed in this PR; this requirement is for private networks, from what I understand. However, I added a small section at the end to point readers to that part of the …
> 463 additional info for a node's ports

- config/sidebar.config.js
- source/docs/casper/operators/becoming-a-validator/bonding.md
- source/docs/casper/operators/becoming-a-validator/inactive-vs-faulty.md
- source/docs/casper/operators/becoming-a-validator/recovering.md
I've taken the content from [here] (https://github.com/casper-network/casper-node/wiki/Recover-from-Validator-Ejection) and [here](https://github.com/casper-network/docs/issues/87#issuecomment-1119397525), edited it, and ran through the commands. Once we bring this content into the docs, we should point the wiki page to it.
@ACStoneCL
> 87 - Document validator eviction

- source/docs/casper/developers/dapps/sending-deploys.md
Polishes _Sending Deploys_ under _Building dApps_.
These changes are backported from the default branch of [docs-new](https://github.com/casper-network/docs-new) repository, so you can preview them [live here](https://docs-new.casper.network/developers/dapps/sending-deploys/).
Original PR authored by @jonas089: https://github.com/casper-network/docs-new/pull/122 (**note:** it was reviewed by Karan).
> Polish Sending Deploys page

- source/docs/casper/developers/json-rpc/types_chain.md
- source/docs/casper/developers/json-rpc/types_cl.md
Polished version of types pages, mainly better explanation of _AccountHash_.
These changes are backported from the default branch of [docs-new](https://github.com/casper-network/docs-new) repository.
Original PR authored by @jonas089: https://github.com/casper-network/docs-new/pull/15.
> Improve AccountHash explanation

- config/sidebar.config.js
- source/docs/casper/concepts/deploy-and-deploy-lifecycle.md
- source/docs/casper/concepts/design/casper-design.md
New page "Deploy & the Deploy Lifecycle" under _Concepts_.
These changes are backported from the default branch of [docs-new](https://github.com/casper-network/docs-new) repository, so you can preview them [live here](https://docs-new.casper.network/deploy-and-deploy-lifecycle/).
Original PR authored by @caspermel: https://github.com/casper-network/docs-new/pull/145.
> Add "Deploy & the Deploy Lifecycle" concept

- config/sidebar.config.js
- source/docs/casper/concepts/design/casper-design.md
- source/docs/casper/concepts/global-state.md
- source/docs/casper/concepts/index.md
- source/docs/casper/operators/setup-network/create-private.md
- source/docs/casper/resources/build-on-casper/casper-open-source-software.md
New page "Global State" under _Concepts_.
These changes are backported from the default branch of [docs-new](https://github.com/casper-network/docs-new) repository, so you can preview them [live here](https://docs-new.casper.network/concepts/global-state/).
Original PR authored by @caspermel: https://github.com/casper-network/docs-new/pull/160.
> Add "Global State" concept

- config/sidebar.config.js
- source/docs/casper/concepts/design/casper-design.md
- source/docs/casper/concepts/design/index.md
- source/docs/casper/concepts/global-state.md
I had change requests for PR 980 that I couldn't submit due to a GH issue today. See 
[Notes for PR9980.pdf](https://github.com/casper-network/docs/files/11082299/Notes.for.PR9980.pdf).
Also, I noticed that we have an incorrectly formatted note on [the page.](https://docs.casper.network/concepts/global-state/)
@ACStoneCL
> Updates post PR 980

- source/docs/casper/developers/dapps/monitor-and-consume-events.md
Typically N is only used as non-buffering when looking at event streams themselves.  So this is only used with curl on the 9999 ports.  For 8888 examples, we don't need N and should have only curl -s.
> Minor update in curl command

- source/docs/casper/developers/dapps/sdk/index.md
Polishes existing Building-dApps/Intro to SDKs.
These changes are backported from the default branch of [docs-new](https://github.com/casper-network/docs-new) repository, so you can preview them [live here](https://docs-new.casper.network/sdk/).
Original PR authored by @dylanireland: https://github.com/casper-network/docs-new/pull/148.
> Polished intro to SDKs

- .github/workflows/main.yml
It prevents triggering `deploy-prod` job on forked repositories. For example we have [docs-new](https://github.com/casper-network/docs-new/tree/dev-new/source/docs/casper), and every time we sync `dev` branch, it overwrites pages in our environment.
It is common problem that is solved by adding condition - see https://github.com/actions/runner/issues/859.
> Prevent running deploy-prod on forks

- src/plugins/docusaurus-plugin-navdata/src/index.ts
Prevent build from succeeding when _navdata_ assets cannot be downloaded. This should prevent scenarios like one we saw yesterday:
This is backport of navdata changes in https://github.com/casper-network/docs-new/pull/194.
> Throw error when failed to download NavData asset

- config/sidebar.config.js
- source/docs/casper/developers/dapps/sdk/client-library-usage.md
New page "SDK Client Library Usage" under _Building dApps - SDK Client Libraries_, that contains unified (multi-block) SDK usage. In future it should replace all other dedicated pages, but for now we leave them, as not every information was moved yet.
These changes are backported from the default branch of [docs-new](https://github.com/casper-network/docs-new) repository, so you can preview them [live here](https://staging.docs.casper.network/developers/dapps/sdk/client-library-usage/).
Original PR authored by @dylanireland: https://github.com/casper-network/docs-new/pull/171.
> Add basic unified SDK page

- config/sidebar.config.js
- source/docs/casper/concepts/design/reading-and-writing-to-the-blockchain.md
- source/docs/casper/resources/tutorials/advanced/index.md
- source/docs/casper/resources/tutorials/advanced/storage-workflow.md
Expanded information on the methods of storage for Casper networks.
Closes #866 
Includes work previously done by @ipopescu to refine the existing [document](https://docs.casperlabs.io/concepts/design/reading-and-writing-to-the-blockchain/) as well as a new document "Reading and Writing to Global State using Rust" that outlines more specifics.
Writing: @ipopescu / Tech: @gRoussac 
FYI: @darthsiroftardis
> 866 Reading and Writing to the Blockchain

- config/sidebar.config.js
- source/docs/casper/concepts/economics/runtime.md
- source/docs/casper/concepts/economics/staking.md
Fixes confusing titles for economics sub-articles.
Closes #1001 
@ACStoneCL
> Making economics article subtitles in the sidebar self-explanatory

- src/assets/scss/_global.scss
Add commit with UI fix - responsive header size - that was missed during last changes synchronization - see https://github.com/casper-network/docs-new/pull/191#issuecomment-1488596586. This will improve size of titles displayed on smaller screen.
This is backport of https://github.com/casper-network/docs-new/commit/f18cdf15ef717118adb3b471c67e75f131205d5a, and you can preview it [live here](https://staging.docs.casper.network/).
> Make header font-size responsive

- .github/templates/.env.production.j2
- .github/workflows/main.yml
- config/algolia.config.js
- docusaurus.config.js
Dehardcode Algolia configuration, by utilizing config file and repository secrets/variables.
Closes #1030.
This is backport of https://github.com/casper-network/docs-new/commit/7b4eccf583203e012013422c0a2acb8721d5421f and https://github.com/casper-network/docs-new/commit/8b5bffd4ce38d8faea3feaaa70e5fca64114b2ee. New repository variable was already configured:
> Dehardcode Algolia config

- source/docs/casper/developers/dapps/sdk/client-library-usage.md
- source/docs/casper/developers/dapps/sdk/script-sdk.md
This PR fixes 2 bugs:
- `/rpc` suffix was recently removed - https://github.com/casper-network/docs/commit/cb101b863b4e8401b31281c0c25679e85dcf8d10 - but it is required (I tested it).
- Cryptographic algorithm in JS SDK are accessible via CamelCase, not UPPERCASE.
> Fix unified SDK issues

- source/docs/casper/developers/writing-onchain-code/simple-contract.md
Polishes _Writing Basic Smart Contract_ under _Developers - Writing On-Chain Code_.
These changes are backported from the default branch of [docs-new](https://github.com/casper-network/docs-new) repository, so you can preview them [live here](https://docs-new.casper.network/developers/writing-onchain-code/simple-contract/).
Original PR authored by @KMCreatesWorlds: https://github.com/casper-network/docs-new/pull/123.
> Polish Writing Basic Smart Contract page

- .github/workflows/main.yml
In [docs-new repo](https://github.com/casper-network/docs-new/) we observed Docusaurus cache issues - see https://github.com/casper-network/docs-new/issues/200 for details.
This PR is backport of [commit that fixes cache issues](https://github.com/casper-network/docs-new/commit/b99c9aac54f2bdba7217e3662d0f8d206d94bab4).
> Clear Docusaurus cache before build

- docusaurus.config.js
Invalid `gtag` config placement - build failing after https://github.com/casper-network/docs/pull/1068:
> Error:  Unable to build website for locale en.
> Error:  Error: The "gtag" field in themeConfig should now be specified as option for plugin-google-gtag. For preset-classic, simply move themeConfig.gtag to preset options. More information at https://github.com/facebook/docusaurus/pull/5832.
>
> Move gtag config from theme to preset options

- config/navbar.config.js
I guess the repo was renamed from `docs-app`to `docs` but not updated in the navigation. This PR will update the link and removes the unecessary redirect.
N/A
No idea
> Update link to the docs repo

- config/sidebar.config.js
- source/docs/casper/developers/dapps/prerequisites.md
New dApp page "Prerequisites".
These changes are backported from the default branch of [docs-new](https://github.com/casper-network/docs-new) repository, so you can preview them [live here](https://staging.docs.casper.network/developers/dapps/prerequisites/).
Original PR authored by @dylanireland: https://github.com/casper-network/docs-new/pull/141.
> Add dApps prerequisites

- source/docs/casper/operators/becoming-a-validator/unbonding.md
Fixes the wait period which is wrong in the current docs.
Reference for the correct wait period as of 1.4.13:
https://github.com/casper-network/casper-node/blob/release-1.4.13/resources/production/chainspec.toml#L41
Also added hours since humans are currently more used to count in hours.
N/A
You decide
> Fix and clarify wait period for unbonding

- source/docs/casper/operators/setup/install-node.md
It enables the built-in capabilities of `casper-client` to generate and activate a bash auto completion script.
Maybe another place in the docs is better - feel free to adjust.
You decide
> Add step for casper-client's auto completion

- source/docs/casper/developers/cli/transfers/verify-transfer.md
Improved _[Verifying a Transfer](https://docs.casper.network/developers/cli/transfers/verify-transfer/)_, mainly:
- Add sample output for `get-state-root-hash`
- Merge sections about querying account state - there is no need to have 2 identical sections, one mentioning to use *source*, another mentioning *target*.
- Merge sections about querying purse - same as above.
- Move `Querying Transfer Details` to top - for me it follows logical order: after we make transfer we want to get execution details, then we can explore the side effects (query account, purse).
- Explained how to get `transfer-` identifiers from deploy.
**Because of those moves/merges, reviewing commit by commit is advised here.**
Related task: https://github.com/casper-network/docs-new/issues/69.
> Polished "Verifying a Transfer"

- source/docs/casper/operators/setup/hardware.md
This PR adds information to the Operator Hardware Requirements specifying CPU architecture necessary to use official binaries.
Closes #975 
[State required CPU #975](https://github.com/casper-network/docs/issues/975)
@ipopescu
> Adding CPU Requirements for Running a Node

- source/docs/casper/resources/tutorials/beginner/upgrade-contract.md
While trying to fix a formatting issue, I noticed that this document has too many long notes. Also, I think we should use numbered lists whenever possible, until the bullet points are fixed.
Closes #1130 
@ACStoneCL
> Fix formatting in upgrade tutorial

- source/docs/casper/developers/dapps/sdk/client-library-usage.md
Add staking to client library usage document
These changes are backported from the default branch of [docs-new](https://github.com/casper-network/docs-new) repository, so you can preview them [live here](https://staging.docs.casper.network/developers/dapps/sdk/client-library-usage/#staking).
Original PR authored by @dylanireland: https://github.com/casper-network/docs-new/pull/198.
> Add staking section to unified SDK

- source/docs/casper/concepts/callstack.md
- source/docs/casper/developers/json-rpc/json-rpc-informational.md
- source/docs/casper/developers/json-rpc/json-rpc-transactional.md
This PR adds example code for the `specualtive_exec` and `info_get_chainspec` JSON-RPC endpoints.
Closes #987 
[Update 1.5 Endpoint JSON-RPC Example Code #987](https://github.com/casper-network/docs/issues/987)
@ipopescu
> 987 Updating 1.5 JSON-RPC with Example Code

- source/docs/casper/operators/setup/node-endpoints.md
This PR adds the firewall rules from the support portal.
Closes #1039 
@ACStoneCL
> 1039 - Add firewall rules for operators

- source/docs/casper/concepts/callstack.md
This PR further clarifies best practices for avoiding the call stack depth limitations.
Closes #1088 
[Clarify Call Stack Depth Best Practices #1088](https://github.com/casper-network/docs/issues/1088)
Writing: @ipopescu Tech: @darthsiroftardis
> 1088 Call Stack Best Practices

- config/sidebar.config.js
- source/docs/casper/operators/index.md
- source/docs/casper/operators/setup/install-node.md
- source/docs/casper/operators/setup/open-files.md
> 1036 Update open file limit for operators

- config/sidebar.config.js
- source/docs/casper/operators/advanced-topics/moving-node.md
- source/docs/casper/operators/index.md
Merges content from the wiki and support portal. Once the content is live, the support portal article could point to this refurbished article in the docs. FYI @cryofracture.
This PR builds on the structure from PR 1038, so I would like to merge it there first.
Closes #1037 
@ACStoneCL 
FYI @cryofracture
> 1037 Moving a node to a new machine

- config/sidebar.config.js
- source/docs/casper/operators/advanced-topics/archiving-and-restoring.md
- source/docs/casper/operators/advanced-topics/moving-node.md
- source/docs/casper/operators/index.md
Add content from the wiki for archiving and restoring a node database.
Closes #1038 
@ACStoneCL
> 1038 Archiving and restoring a node DB

- source/docs/casper/developers/cli/redelegate.md
- Adds details on how to call the "redelegate" entry point from the system auction contract
- Updated examples and explanations of arguments
Note: while working on this PR, I realized that the "delegate.md" and "undelegate.md" also need to be updated to include calling the system auction. I will create a new ticket for testing and updating these pages.
Closes #898 
Here is the account used for testing this functionality: https://integration.cspr.live/account/01360af61b50cdcb7b92cffe2c99315d413d34ef77fadee0c105cc4f1d4120f986.
Here is the redelegate using the system auction:
https://integration.cspr.live/deploy/a10872dad686b2bde4c3d5a57f571a8b0a82cc6efc822e43c08f82a2fe8b83aa
Here is the redelegate using the "redelegate.wasm" contract: …
> 898 - update redelegate details for 1.5

- source/docs/casper/developers/dapps/sdk/go-sdk.md
- source/docs/casper/developers/dapps/sdk/index.md
- source/docs/casper/resources/build-on-casper/casper-open-source-software.md
Replaced the old SDK with the one created at MAKE in the official Casper documentation:
The documentation is available under the following links:
- [SDK Client Libraries | Casper](https://docs.casper.network/sdk/) 
- [Ecosystem Open-Source Software | Casper](https://docs.casper.network/resources/build-on-casper/casper-open-source-software/) 
- [Golang SDK | Casper](https://docs.casper.network/developers/dapps/sdk/go-sdk/) 
The old SDK entries should be fully replaced
> Change links and examples for the new Go SDK

- source/docs/casper/users/token-transfer.md
Image paths were broken during restructuring at some point. This PR fixes said paths.
Closes #1156
[Correct Image Paths for Transfer Tutorial #1156](https://github.com/casper-network/docs/issues/1156)
@ShalmaliCL
> Correct Image Paths for the Block Explorer Transfer Tutorial

- source/docs/casper/concepts/callstack.md
- source/docs/casper/concepts/design/casper-design.md
- source/docs/casper/concepts/design/networking-protocol.md
- source/docs/casper/concepts/dictionaries.md
- source/docs/casper/concepts/list-auth-keys.md
- source/docs/casper/developers/dapps/sdk/script-sdk.md
- source/docs/casper/developers/writing-onchain-code/getting-started.md
- source/docs/casper/resources/tutorials/advanced/list-cspr.md
- Updates docs.rs links to the latest version. I have checked all docs.rs links and TODOs.
- Removes the link to [get_immediate_caller](https://docs.rs/casper-types/1.5.0/casper_types/system/mint/trait.RuntimeProvider.html#tymethod.get_immediate_caller), which is not available in the latest version. We can point to [get_call_stack](https://docs.rs/casper-contract/3.0.0/casper_contract/contract_api/runtime/fn.get_call_stack.html) instead. Adding @deuszex for a quick technical check here.
- Removed link and content related to the erc20 client that breaks the build. Point to the cep78 client instead of the cep47 client since we are changing this file.
Closes #999
@ACStoneCL and @deuszex
> 999 - Update docs.rs links for 1.5 release

- docusaurus.config.js
- src/plugins/docusaurus-plugin-navdata/src/convertData.ts
- src/plugins/docusaurus-plugin-navdata/src/index.ts
- src/plugins/docusaurus-plugin-navdata/src/interfaces/navbar/footerData.ts
Include new text property in NavData plugin (connected with Directus) that will be used in the footer to manage cookies, i.e.:
This is backport of **Navdata plugin** changes introduced in [Dev cookies banner PR](https://github.com/casper-network/docs-new/pull/207).
**Note:** Above mentioned PR was reviewed by @bradjohnl and @andrzej-casper.
> Cookie banner - navdata changes

- source/docs/casper/operators/becoming-a-validator/bonding.md
- source/docs/casper/operators/becoming-a-validator/recovering.md
- source/docs/casper/operators/setup/joining.md
Adds information on the activate_bid entrypoint when validators are recovering from eviction. The current [documentation](https://docs.casper.network/operators/becoming-a-validator/recovering/#activating-the-bid) only mentions the "activate_bid.wasm", which is more expensive.
Closes #1147 
I haven’t been able to test the "activate_bid" entry point yet. It takes time to simulate the eviction.
However, I am pretty confident that the instructions are correct. I will attempt to run them before the sprint ends (in parallel with the review). It would be great to get a tech reviewer to confirm their correctness, in case I cannot simulate the eviction.
I relied on the instructions that were already documented, and followed the same pattern as in the `bonding.md` file. I’ve also checked the code …
> 1147 - Operators:  use the "activate_bid" entrypoint

- source/docs/casper/developers/json-rpc/json-rpc-informational.md
This reintroduces the `query_balance` endpoint into the `feat-1.5.0` branch, alongside some additional fixes necessary for the 1.5 update.
Closes #1148
[Reintroduce query_balance end point to 1.5 branch and check CHANGELOG for more changes. #1148](https://github.com/casper-network/docs/issues/1148)
Editing: @ipopescu / Tech: @darthsiroftardis
> 1148 Reintroduce `query_balance` endpoint to `feat-1.5` docs branch

- source/docs/casper/developers/writing-onchain-code/best-practices.md
Recent changes make inlining more important, so I've expanded our best practices documentation to mention it.
Closes #1143 
[Outline Inlining in Smart Contract Best Practices #1143](https://github.com/casper-network/docs/issues/1143)
@ipopescu
> 1143 Including Inlining in Smart Contract Best Practices

- .github/workflows/main.yml
Currently Algolia config is stored in repository secrets, although it is not secret at all:
That is why we should use variables instead - it will make configuration inspection easier.
> Make Algolia configurable via GitHub vars (not secrets)

- source/docs/casper/concepts/accounts-and-keys.md
- source/docs/casper/concepts/design/casper-design.md
- source/docs/casper/operators/setup/non-root-user.md
Minor updates in the `source/docs/casper/concepts/accounts-and-keys.md` file.
The content was already up-to-date, so I only made minor changes to the title casing and terminology to avoid saying "Ethereum keys".
I reverted commit 511e28f95d8f19a52a80ea96fdfd64d1552071dd because it wasn't correct. Those keys are created for the connection to the validator node, not for use on the Casper network.
Closes #848 
@ACStoneCL
> 848 - Minor updates for generating keys

- .github/workflows/main.yml
Converts all repository's "_secrets_" that are public - `SITE_URL`, `BASE_URL` and `PROD_PAGES_FQDN` - into _variables_, as it will make configuration inspection easier.
This is **finalization** of the following work:
- https://github.com/casper-network/docs/commit/be717324e3fd65e9d297b55ba8f6b9a31cd37d0b
- https://github.com/casper-network/docs/pull/1184 
Repository variables are already created - according to the current "secrets":
**Note:** `BASE_URL` is optional and it was not used yet.
**TODO:** Remove unnecessary secret, when this PR gets merged.
> Convert all public secrets to vars

- source/docs/casper/resources/migrate.md
Updates the content for PR #1178. A few callouts to keep in mind for the future:
- The summary at the end isn’t really a summary of the previous sections, so I renamed it
- In the Casper tab, I removed the repetition of Casper (ex “on the Casper Network”, or “in Casper”)
- The `call` function is like a main function, not a constructor. I rewrote this part.
- Removed passive voice when possible. Ex: “data persists” instead of “data is persisted”. Another ex: “These data structures can organize” vs. “These data structures can be used to organize”
- We should not advise on another chain. Ex for Near: “When creating state variables, it is advisable to use SDK Collections.” I tried to remove any recommendations for other chains.
@KMCreatesWorlds 
@RitaMAllenCA I am not connecting an issue …
> Editing pass for PR 1178

- source/docs/casper/developers/dapps/template-frontend.md
This typo was missed in a code review for PR #1047
> Fix typo in "add frontend template"

- source/docs/casper/developers/writing-onchain-code/best-practices.md
An oldie but goldie--tips from Fraser on reducing Wasm size. I've added them to best practices, and linked to the cep18 contract.
Closes #112 
@ACStoneCL
> Add tips to reduce WASM size

- config/sidebar.config.js
- source/docs/casper/developers/dapps/speculative-exec.md
This PR introduces a guide for use of the `speculative_exec` endpoint in the Casper client.
Closes #1180 
[Create a Guide to using the speculative_exec endpoint #1180](https://github.com/casper-network/docs/issues/1180)
Editing: @ipopescu / Tech @bpr or assignee.
> 1180 Guide for use of Speculative Execution

- src/assets/scss/_global.scss
Remove CSS classes that caused bullet points to be not rendered.
Closes [#1203](https://github.com/casper-network/docs/issues/1203).
> Fix missing bullet points

- docusaurus.config.js
- src/theme/DocPage/index.jsx
- static/js/loadtags.js
This is backport of fix introduced in https://github.com/casper-network/docs-new/pull/209:
> Fix GTM data layer not being correctly updated when cookies preferences changes.
This was already merged to https://staging.docs.casper.network/, and 
Mare Hojc confirmed it works correctly.
> Cookie banner - fix GTM data layer

- source/docs/casper/operators/setup/basic-node-configuration.md
This introduces details for enabling speculative execution for node operators.
N/A
@ipopescu
> Information on enabling Speculative Execution

- source/docs/casper/developers/json-rpc/json-rpc-informational.md
As per a note from @gyroflaw, `execution_results` within `info_get_deploy` is an array, not an object.
@gyroflaw
> Execution Results Fix

- config/sidebar.config.js
- source/docs/casper/concepts/glossary/C.md
- source/docs/casper/operators/setup-network/chain-spec.md
- source/docs/casper/operators/setup-network/genesis.md
- source/docs/casper/operators/setup-network/index.md
- source/docs/casper/resources/advanced/multi-sig/multi-sig-workflow.md
This PR adds the content from the 1.5.2 Mainnet chainspec to our documentation, with some small additions introduced by commit 969cf9ef94c063edf887705131d48a2dc711585e. The main file is [here](https://github.com/casper-network/docs/blob/969cf9ef94c063edf887705131d48a2dc711585e/source/docs/casper/operators/setup-network/chain-spec.md).
I left a few TODOs for open questions in the file so I can resolve them during the review process:
1. For the 'hard_reset' description, can we say: "Specifies whether or not the latest blocks will be cleared back to the switch block just before the activation point in case of resetting the node"? When I see 'hard_reset', I think this happens when a node needs to be reset.
2. Where can I find the genesis_hash to link to it? It is mentioned in the `name` …
> 1222 chainspec documentation

- source/docs/casper/resources/build-on-casper.md
Fix for [recently failing build](https://github.com/casper-network/docs/actions/runs/5893040610/job/16071744501):
**Note:** I got new URL directly from @KillianH.
> Update Casper Snap URL

- .github/workflows/main.yml
Automatic preview for pull requests:
**Base part**
For every pull request `deploy-preview` job is executed, and with [nwtgck/actions-netlify@2.1](https://github.com/nwtgck/actions-netlify) action:
- deployment is published to Netlify, then
- comment with URL is added to pull request.
This part requires 2 new repository secrets (already filled):
- Netlify auth token: `PREVIEW_NETLIFY_AUTH_TOKEN`,
- Netlify site ID: `PREVIEW_NETLIFY_SITE_ID`.
**Directus part**
Since this deployment is exactly like the local one, it would not include site header/footer (as it requires Directus setup for getting text data). Therefore, I decided to go step further and overcome this bad design with a quick workaround. I introduced additional build step *Template credentials - preview*, that fills `.env` file …
> CI/CD: Setup preview deployments

- .github/workflows/main.yml
_We often experience broken external link and this really affects our CI/CD pipeline, that we cannot build/merge until such link is changed/removed. Then all PRs must be updated to include such fix, and this unnecessarily slows us down._
Therefore, I moved external links validation to separate job, so this would not affect `build` and still allow to merge PR.
**Demo:**
> CI/CD: Allow external links failure

- source/docs/casper/operators/maintenance/moving-node.md
- source/docs/casper/resources/advanced/list-cspr.md
Removing one of the methods for moving a node based on [this Slack message](https://casper-labs-team.slack.com/archives/C0135SDEGUC/p1692907983926009)
N/A
@sacherjj
> Removing a Method from the "Move A Node" Docs

- source/docs/casper/operators/setup/install-node.md
Based on a Slack conversation, the `trusted_hash` information in the Installing a Node document needs to be updated.
[Slack Conversation](https://casper-labs-team.slack.com/archives/C0135SDEGUC/p1693581449564239?thread_ts=1693581449.564239&cid=C0135SDEGUC)
@sacherjj
> Hotfix Trusted Hash Instructions for Node Operators

- source/docs/casper/concepts/hash-types.md
- source/docs/casper/concepts/serialization-standard.md
As discussed in the L1 Daily Standup, there is a third type of `PublicKey` that was not externally facing until the release of 1.5. This PR updates instances of `PublicKey` information.
Closes #1270 
[Update PublicKey info to include System #1270](https://github.com/casper-network/docs/issues/1270)
Editor: @ipopescu Tech: @darthsiroftardis
> PublicKey Updates

- config/sidebar.config.js
- source/docs/casper/operators/becoming-a-validator/fast-sync.md
- source/docs/casper/operators/setup/fast-sync.md
- source/docs/casper/operators/setup/install-node.md
While working on something else, I realized we forgot to expose the fast sync introduction when we released 1.5. I refreshed the file and added it in the setup section.
@ACStoneCL
> Fast sync intro

- source/docs/casper/developers/cli/transfers/verify-transfer.md
- source/docs/casper/developers/json-rpc/json-rpc-informational.md
- source/docs/casper/developers/json-rpc/minimal-compliance.md
- source/docs/casper/resources/beginner/querying-network.md
Removing the "state_get_balance" documentation and examples, since it has been deprecated in favor of "query_balance".
- The examples in `querying-network.md` are the actual commands and responses.
- The examples in `verify-transfer.md` are taken from `querying-network.md`, but have been modified to fit the tutorial (using the same account hashes and state root hash, to match the transfer flow). Eventually, we need to refresh the entire tutorial with fresh examples.
- In `minimal-compliance.md`, I found the following explanation confusing, so I'd like to simplify it by removing the crossed-out section. If it adds value to this point, please let me know.
[`chain_get_state_root_hash`](./json-rpc-informational.md#chain-get-state-root-hash) - The state root hash is one of the several [global …
> Replace state_get_balance with query_balance

- source/docs/casper/resources/build-on-casper.md
Remove flask suffix to Metamask
Remove flask suffix to Metamask since Snaps is released in the official version of Metamask.
> Remove flask suffix to Metamask

- src/assets/scss/_global.scss
Workaround to restore default's Docusaurus font styles, for better readability:
Closes #1287.
> Restore font styles for headings and menu items

- source/docs/casper/developers/json-rpc/json-rpc-transactional.md
It changes the `account_put_deploy` example slightly to pass validation on the current `dev` version of casper-node.
When on-boarding I was trying it examples in the docs and I noticed a few issues:
- the amount in the example is `I32`, but that seems to be disallowed in casper-node, leading to an error `failed to parse transfer 'amount' as U512`
- the Transfer object doesn't have a `target`, which is currently also rejected in casper-node: `missing transfer 'target' runtime argument`
- casper-node currently enforces a minimal transfer amount of `2500000000`, so I've set the amount to that as well
> Update account_put_deploy example to work with current casper-node

- source/docs/casper/concepts/design/casper-design.md
Fixed a typo that breaks MD rendering in casper-design.md
Found it while brosing the docs.
> Fix a typo that breaks MD rendering in casper-design.md

- source/docs/casper/resources/advanced/multi-sig/multi-sig-workflow.md
Adds additional verification commands to the multi-sig tutorial.
Closes #1286 
@ACStoneCL
> Add verification commands in the multi-sig tutorial

- .github/workflows/main.yml
- Reduces duplicated CI/CD checks.
- Prevents pipelines from running on arbitrary branches.
Closes #1290.
> Limit CI/CD push trigger to `dev` branch only.

- source/docs/casper/operators/aws-nodes/3-instances.md
Taking into account that on AWS one must consider not only the instance's CPUs but also their equivalence to the vCPUs (virtual CPUs) offered by Amazon instances, the table specifies the equivalent for the recommended instance (t3.2xlarge).
@bradjohnl @ipopescu
> specify number of real cores and threads per core

- source/docs/casper/concepts/design/casper-design.md
- source/docs/casper/concepts/serialization-standard.md
Clarifies URef access rights in Serialization Standard docs. See [1310](https://github.com/casper-network/docs/issues/1310) for follow-up work.
Closes #1307
[Clarify URef Access Rights Throughout Docs #1307](https://github.com/casper-network/docs/issues/1307)
@ipopescu
> 1307 Clarifying URef AccessRights

- config/sidebar.config.js
- source/docs/casper/resources/tokens/cep18/full-tutorial.md
- source/docs/casper/resources/tokens/cep18/query.md
- source/docs/casper/resources/tokens/cep18/quickstart-guide.md
- source/docs/casper/resources/tokens/cep18/tests.md
- source/docs/casper/resources/tokens/cep18/transfer.md
- source/docs/casper/resources/tokens/cep78/introduction.md
- source/docs/casper/resources/tokens/cep78/js-tutorial.md
- source/docs/casper/resources/tokens/cep78/modalities.md
- source/docs/casper/resources/tokens/cep78/reverse-lookup.md
- source/docs/casper/resources/tokens/cep78/using-casper-client.md
- source/docs/casper/resources/tokens/index.md
This PR introduces documentation held in the [CEP-18](https://github.com/casper-ecosystem/cep18) and [CEP-78](https://github.com/casper-ecosystem/cep-78-enhanced-nft) repositories into the main documentation site.
A new index has been added and documents edited as necessary, but this is mostly replication of previously reviewed content.
Closes #1315
[Add 'Casper Token Standards' to 'Resources' tab #1315](https://github.com/casper-network/docs/issues/1315)
@ipopescu
> 1315 Adding Casper Token Standard Docs to Main Site

- config/sidebar.config.js
- source/docs/casper/developers/dapps/uref-security.md
This PR introduces a new document to the `Resources` tab that includes very specific information about URef `AccessRights`
Closes #1310
[Create a Tutorial for Changing URef Access Rights #1310](https://github.com/casper-network/docs/issues/1310)
Editing: @ipopescu Tech: @gRoussac
> 1310 URef AccessRights Clarification Tutorial

- source/docs/casper/resources/tokens/cep18/transfer.md
I noticed that the most recent update to the CEP-18 Docs hadn't made it into the main documentation site.
N/A
@ipopescu
> Updating CEP-18 docs

- source/docs/casper/developers/cli/redelegate.md
This PR clarifies that redelegations share the 500 CSPR minimum threshold amount.
[Slack Conversation](https://casper-labs-team.slack.com/archives/C0135SDEGUC/p1699550381376029)
@ipopescu
> Redelegation Clarification

- config/sidebar.config.js
- source/docs/casper/developers/cli/opcode-costs.md
- source/docs/casper/operators/setup-network/chain-spec.md
This PR introduces a new page that clearly states OpCode costs in the `Developers` section, as well as updating tables in the Private Network docs within `Operators`
This PR addresses 1.5.4 changes and should not be merged until 1.5.4 is live.
Closes #1318
[Document OpCode Costs #1318](https://github.com/casper-network/docs/issues/1318)
@ipopescu
> 1318 OpCode Documentation [1.5.4] 

- source/docs/casper/developers/writing-onchain-code/upgrading-contracts.md
- source/docs/casper/resources/beginner/upgrade-contract.md
Adding information about the `enable_contract_version` function in 1.5.4.
Closes #1325
[Document the Ability to Re-enable a Disabled Contract Version #1325](https://github.com/casper-network/docs/issues/1325)
@ipopescu
> 1325 Adding information about enabling contracts.

- .github/workflows/main.yml
- config/sidebar.config.js
- source/docs/casper/developers/essential-crates.md
- source/docs/casper/developers/index.md
- source/docs/casper/developers/prerequisites.md
- source/docs/casper/developers/writing-onchain-code/getting-started.md
This PR adds a list of important crates for development. The ”Getting Started” and “Prerequisites” page link to the list. The rest of the pages in writing & testing contracts already have links.
Closes #1238
@ACStoneCL
> Add info on Rust crates and documentation

- DEVELOPERS.md
- README.md
- config/navbar.config.js
- writing-style-guide.md
This PR highlights ways to contribute to the documentation. On docs.casper.network, the GitHub link could open the documentation README.md directly to make the contribution options even clearer. Closes #927 
@ACStoneCL
> 927 - Highlight ways to contribute to the docs

- source/docs/casper/developers/cli/sending-deploys.md
TTL is now 18 hours rather than 1 day. This PR changes the value in the "Sending Deploy" doc.
[This Slack Conversation](https://casper-labs-team.slack.com/archives/C0135SDEGUC/p1704208825340459)
@sacherjj
> TTL Update

- .github/workflows/main.yml
- source/docs/casper/concepts/hash-types.md
- source/docs/casper/concepts/serialization-standard.md
- source/docs/casper/developers/json-rpc/json-rpc-informational.md
- source/docs/casper/developers/json-rpc/json-rpc-transactional.md
- source/docs/casper/developers/json-rpc/types_chain.md
This PR grew out of control from the Account/Contract merge ticket, but covers many items we would need to finish for 2.0.
It includes all (current) new endpoints for the JSON-RPC and associated types, as well as some of the account/contract merge - but I will finish that in another PR.
Closes #1342
Closes #1317
[Document New JSON-RPC API Endpoints #1317](https://github.com/casper-network/docs/issues/1317)
[Update state_get_account_info in the JSON-RPC Docs #1342](https://github.com/casper-network/docs/issues/1342)
// Tag whoever needs to review. If you're not sure, leave blank.
> JSON-RPC API Updates for 2.0

- source/docs/casper/operators/setup/install-node.md
Fixes the broken link to a required package during installation as the package no longer exists. The package is replaced with a higher version one. Also, adds the -f flag to curl to ensure it fails if the package is not found.
@ipopescu
> Fix broken link for package required for compatibility with Ubuntu 22.04

- source/docs/casper/resources/advanced/transfer-token-to-contract.md
As requested in [this thread](https://casper-labs-team.slack.com/archives/C01J86T699U/p1705923063189069?thread_ts=1705837279.975239&cid=C01J86T699U), I added a note clarifying that token transfers must be handled via stored contract (not stored session).
@ACStoneCL
> 1357 - Clarification regarding token transfers

- source/docs/casper/developers/dapps/sdk/python-sdk.md
[Recent commits](https://github.com/casper-network/casper-python-sdk/commit/4355462b979d03a93cd401b5e51e8ef3be5b66c0) to the Python SDK have caused an external link failure. This updates the installation instructions so that the external link is no longer needed.
[Removal of requirements.txt](https://github.com/casper-network/casper-python-sdk/commit/4355462b979d03a93cd401b5e51e8ef3be5b66c0)
@ipopescu
> Remove Broken Python SDK Link

- .github/dependabot.yml
Creating dependabot config to enable automated PRs for dependency upgrades, boosting security and maintainability.
This PR introduces a Dependabot configuration file to the repository. This configuration enables automated pull requests for dependency updates, ensuring our dependencies are up-to-date, secure, and maintained efficiently.
Closes #<enter issue number if applicable>
This change will streamline the process of keeping dependencies updated, reducing the manual effort required and helping to avoid potential security vulnerabilities associated with outdated packages. 
@ACStoneCL, @ipopescu
> Add Dependabot Configuration for Automated Dependency Management

- source/docs/casper/developers/dapps/setup-nctl.md
This PR introduces few enhancements to the existing `nctl` tutorial:
1. Simplified Command Execution: Removes unnecessary `$` and `(env)` prefixes from commands. This allows users to copy and paste commands directly into their terminals without modification.
2. Explicit Bash Shell Instruction: Adds a dedicated step outlining the need to switch to the bash shell for successful command execution.
3. this PR renumbers the steps to avoid duplication (previously, two steps were labeled "Step 15").
Closes #
This PR fixes all the issues I run into while trying to follow the `nctl` tutorial for the first time.
> nctl tutorial improvements 

- source/docs/casper/developers/writing-onchain-code/testing-contracts.md
- source/docs/casper/resources/beginner/counter/walkthrough.md
- source/docs/casper/resources/beginner/upgrade-contract.md
- Update the code examples to use the latest versions of dependencies and replace `DEFAULT_RUN_GENESIS_REQUEST` with `PRODUCTION_RUN_GENESIS_REQUEST` (The counter code was already updated)
- Add a `tip` section where testing time sensitive functions in a smart contract is explained
- Add `Adding New Fields During Upgrades` section where adding new `named_keys` to the smart contract on update is explained.
- Update the docs to list the `v3` version of the counter that is introduced in this PR https://github.com/casper-ecosystem/counter/pull/31
- Fix formatting
> Testing smart contracts

- source/docs/casper/developers/dapps/sdk/python-sdk.md
Obsolete Python SDK page content.
Closes #1430
Simplified page by pointing directly to dedicated How To pages within SDK repo itself.
@ipopescu
> 1. Python SDK page updated.

- source/docs/casper/concepts/accounts-and-keys.md
- source/docs/casper/developers/prerequisites.md
Developers need to use the Casper client to generate keys. Otherwise, they won't have access to the secret key fiel.
Closes #1435 
@ACStoneCL
> Add details about the secret key file

- source/docs/casper/resources/condor-for-exchanges.md
This introduces the "Condor Release Notes for Exchanges" as an unlisted document on Github by request of Gate.io
No changes beyond formatting have been made to the previous PDF document.
@ipopescu
> Including Condor for Exchanges in Github by Request

- source/docs/casper/developers/json-rpc/json-rpc-informational.md
- source/docs/casper/developers/json-rpc/types_chain.md
This PR introduces the newly added `info_get_reward` method to the JSON-RPC API documentation.
The JSON-RPC will require additional updates, but this will get necessary information out for third parties.
@ipopescu
> Updating JSON-RPC API with `info_get_reward` method

- config/navbar.config.js
One of the major bullet points to come out of the Starton dev demo was the difficulty finding the Quickstart guide.
This PR rises it to the top level within the docs and makes it clearly visible to anyone searching the site for the first time.
This PR will also trigger the CI/CD build for the main docs repo, updating the DevPortal-level navbars and footer.
[Starton Presentation](https://docs.google.com/presentation/d/1-lf-7lI4DdGijLCgrnQmhKL_1yVkJOZ38vtJmc4umjA/edit?usp=sharing)
@melpadden
> Adding Quickstart to Navbar

- config/navbar.config.js
Promote the Quickstart link to be the first thing a user sees.
Make it open in the same window
Make it a relative Docusaurus link 
// Tag whoever needs to review. If you're not sure, leave blank.
@ACStoneCL
> Promote Quickstart in nav bar

- docusaurus.config.js
Currently, GTM is added but is not working. We can see for example that the web-vitals script which is configured to be loaded on every page from GTM is not loaded.
This occurs because gtag is initialized afterward and also uses ```window.dataLayer```. Data is already being sent to Google Analytics from GTM, so we can remove gtag.
@ACStoneCL
> Fix datalayer because both gtag and gtm was activated

- source/docs/casper/developers/cli/sending-transactions.md
Switching the `Sending Deploys` doc fully to `Sending Transactions` with new procedures fully tested on NCTL with Condor-related branches.
Closes #1456 
[Update content of "Sending Transactions" (Formerly Sending Deploys) #1456](https://github.com/casper-network/docs/issues/1456)
@ipopescu
> 1456 Updating Sending Deploys to Transactions

- source/docs/casper/concepts/transactions.md
This PR introduces a document that specifically outlines the new `Transaction` structure and associated variants.
Closes #1377 
[Document Deploy Restructure #1377](https://github.com/casper-network/docs/issues/1377)
@ipopescu
> 1377 Create Transactions Document

- source/docs/casper/developers/prerequisites.md
This PR adds the public CasperLabs JSON-RPC endpoints as the preferred method of communicating with the network.
The current method encourages choosing from a list of currently online Casper Network peers, many of which may have RPC ports disabled or could theoretically act in malicious ways.
> Added Public CasperLabs JSON-RPC Endpoints

- source/docs/casper/operators/becoming-a-validator/change-bid-public-key.md
- source/docs/casper/operators/becoming-a-validator/index.md
Adds a page describing the new `change_bid_public_key` entry point of system auction contract
> add description for `change_bid_public_key` entry point
